### ISSUE TITLE
[Suggestion] Center position for menu

### ISSUE THREAD

**Issue by benzon** [overextended/ox_lib#100]
Hey

Really wanna use the menu in ox_lib but im missing a center position, so i can center it left center and right center, would give a better feel i think

**Comment by LukeWasTakenn** [comment]
There are currently no plans for this.

**Comment by benzon** [comment]
a shame since the current position feels awkward, having a center postion on the menu would make it so mutch more usefull then having it in cornors, where you potentially got other ui elements.
