### ISSUE TITLE
[Suggestion] Add full string support to addCommand

### ISSUE THREAD

**Issue by DogsGoBark** [overextended/ox_lib#101]
Is it possible to add to `addCommand` to have the option to print everything in the string after the target? For example if you do `/warn me hello, how are you?` it will show `hello how are you` not `hello,`. So in other words, I don't know if it's possible but maybe if they want to do full strings the full-string option has to be the last one?

```lua
lib.addCommand('group.admin', {'warn', 'w'}, function(source, args)
  print(('Target: %s, Message: %s'):format(args.target, args.reason))
end, {'target:number', 'reason:string'})
````

**Comment by thelindat** [comment]
To be honest addCommand isn't really fit for purpose in a few cases and would be better off replaced, but I don't have a good solution yet.

Just use the standard RegisterCommand 🤷

**Comment by DogsGoBark** [comment]
To be honest, I prefer the lib way because of alias support. I was just wondering if there's a way to do a full string like; `full-string` option?
