### ISSUE TITLE
Zone turns out different than in the zone creator

### ISSUE THREAD

**Issue by BerkieBb** [overextended/ox_lib#102]
In zone creator
![image](https://user-images.githubusercontent.com/82737367/191255313-9991c4e6-79cc-43c4-b302-7d8e12e2d093.png)

Data from the zone creator
![image](https://user-images.githubusercontent.com/82737367/191255472-4df25e15-155e-4128-ab00-a08fe531a3a4.png)

Actual zone after using lib.zones.box in a client side resource
![image](https://user-images.githubusercontent.com/82737367/191255636-505a295f-f3e5-47f7-91cd-8caebeb5c637.png)

I don't think it's supposed to be that small compared to what it is in the zone creator

**Comment by DokaDoka** [comment]
balls

**Comment by DokaDoka** [comment]
fixed in https://github.com/overextended/ox_lib/commit/6fdc1973e439f24ec9acd9fc0e42b758df6f916b
