### ISSUE TITLE
[Suggestion] Notifications - Add anchor points 

### ISSUE THREAD

**Issue by EpKouhia** [overextended/ox_lib#104]
Since most of the UI elements tend to be in the corners couple of more options to anchor notifications would be nice.
Example: middle-left, middle-right

**Comment by benzon** [comment]
Tryed to suggest this not that long ago, and it was declined, even tho it would make sence.

**Comment by LukeWasTakenn** [comment]
Chakra does not support middle-left and middle-right anchor points for notifications, implementing this would probably be quite a hassle so there are no plans for it.

However of course if you want to give it a shot and make a PR, it will be looked into.
