### ISSUE TITLE
[Suggestion] Skill Check or Skill Game

### ISSUE THREAD

**Issue by Testaross** [overextended/ox_lib#107]
I have been making many resources for the ox_core platform and am trying to keep them to have very low and preferrably overextended created dependencies for ease of install (see qbcore dependencies). While readying them all for release on my github and watching how the changes to the core are going I notice a major missing feature, a "skill check" or "skill game"

Reasons I believe this will be a helpful feature to the future of the overextended library
- Who doesn't like games? 
- As previously stated, this will allow "developers" such as myself to keep our resource dependencies low for our content made exclusively for the ox platform
- Personally, I would use this for my key system for vehicles, such as lock picking or hotwiring cars
- Could be implemented into the cuffing system to escape
- Major part of the lib for crime, jobs, and items.
- Using a skill game for untrained people using a defib item to revive a dead compatriot

These are some of the reasons for which I personally believe a "skill game" or "skill check" feature would be a positive inclusion into the library. In conclusion, hey lukey, you so fine, you so fine, you blow my mind, hey lukey hey lukey

you are very nice and I appreciate the hard work you put in, for people like myself who are still very new to graphical interfaces your library has allowed me to make a lot of cool things from scratch and share them with others. Thank you for your consideration I hope you are well.

**Comment by thelindat** [comment]
> hey lukey, you so fine, you so fine, you blow my mind, hey lukey hey lukey

where claps
