### ISSUE TITLE
 JS Support

### ISSUE THREAD

**Issue by niunisas** [overextended/ox_lib#11]
Hi, 

Just a quick question, do you plan supporting JS scripts? I mean for example using lib callbacks in JS scripts?

**Comment by thelindat** [comment]
I’m primarily a Lua scripter and need easily reusable code like this, so there’s no plans to make a similar system for the v8 runtime.

There's some resources out there to provide  some of this functionality, and probably available as node modules too.

**Comment by niunisas** [comment]
Understood, I'll make one on my own, and probably reuse some of your code.
