### ISSUE TITLE
[Suggestion] Add static progressbars as description

### ISSUE THREAD

**Issue by BerkieBb** [overextended/ox_lib#113]
![image](https://user-images.githubusercontent.com/82737367/193407872-572207eb-7c38-4499-87fc-766340e6b7f7.png)
Kinda like this, would be cool to have, maybe some grid options as well to like show specific boxes instead of just a line.

**Comment by thelindat** [comment]
Unless something else is wanted, resolved with https://github.com/overextended/ox_lib/pull/166

**Comment by BerkieBb** [comment]
This was actually meant for the description, to provide a static progressbar in there
