### ISSUE TITLE
inputDialog Slider returns null if not moved

### ISSUE THREAD

**Issue by JoeSzymkowiczFiveM** [overextended/ox_lib#116]
I noticed that the slider, if not adjusted/touched before hitting Confirm, will return a null value, even if the min value is the intended choice. You can move it to a new value other than the min and then back and it returns the expected value.

`{ type = 'slider', label = 'ASDF', min = 10, max = 20, step = 2},`

**Comment by LukeWasTakenn** [comment]
Resolved in commit 39f7b6d78a7c2eec71074c3ab1e339003c856f35
