### ISSUE TITLE
[Suggestion] cached selected button on menu

### ISSUE THREAD

**Issue by BerkieBb** [overextended/ox_lib#119]
Basically saving the button you were on inside a menu so if you open the menu you again, you are on that button instead of the first one in the menu

**Comment by LukeWasTakenn** [comment]
I feel like this is something that would be personal preference maybe 🤔

**Comment by thelindat** [comment]
Only case I feel this would be useful is when using nested menus; I mentioned in discord already but we should keep a menu history when opening a new menu. If menu is open and openMenu is triggered again, store the previous menu id; on backspace return to the previous menu and position.

**Comment by BerkieBb** [comment]
Yeah, that was what I had it in mind for
