### ISSUE TITLE
Context menu canClose state

### ISSUE THREAD

**Issue by Aaron-Downham** [overextended/ox_lib#120]
If you register a context menu, without the `canClose` option set (defaults to true), which in turn opens another context menu with `canClose` set to false, there is an issue when navigating back to the parent menu. The ability to close the menu is still disabled in the parent menu, after you navigate back from the sub menu which has it disabled.

I appreciate that might be hard to understand but I've tried to word it the best I can, if needed I can send over a simple example which demonstrates the issue.

**Comment by LukeWasTakenn** [comment]
@Aaron-Downham Can you give me the menu code you can reproduce this on?

**Comment by Aaron-Downham** [comment]
Sorry to waste your time, I've just tried to independently reproduce it outside of my original code for you and found the issue is my side. The child menu was pointing back to a similar menu, but a different ID, and that similar menu was set not to close
