### ISSUE TITLE
need help with ox issue

### ISSUE THREAD

**Issue by snokain** [overextended/ox_lib#13]
[ script:ox_inventory] SCRIPT ERROR: @ox_inventory/modules/init.lua:76: Ox Inventory requires the ox_lib resource, refer to the documentation.

I keep getting this issue , ive tried to troubleshoot and i can not seem to find a resolve.

**Comment by LukeWasTakenn** [comment]
If you have ox_lib already downloaded and you are starting it, make sure the start order is correct.

This **is not** an issue with the resource.
