### ISSUE TITLE
[Suggestion] Title/Description layout for textUI

### ISSUE THREAD

**Issue by davidxd33** [overextended/ox_lib#130]
It would be awesome to add support for a title and description for the textUI just like the notification wrappers are. It would enable beautiful "interact" menus like this:

![](https://i.imgur.com/O5OnajG.png)

**Comment by LukeWasTakenn** [comment]
You can already achieve this with markdown.

![image](https://user-images.githubusercontent.com/39926192/196204088-5bf7b066-6b8f-4600-8c13-e9b9d407c015.png)

```lua
lib.showTextUI('**Stop Working**  \n Interact with [E]', {
    icon = 'door-open',
})
```
