### ISSUE TITLE
txAdmin Error

### ISSUE THREAD

**Issue by NeiZeOne** [overextended/ox_lib#131]
![Unbenannt](https://user-images.githubusercontent.com/114942743/196710360-900b4dc2-c7cd-4d53-979b-9e9815dbf356.PNG)

**Comment by N-fire** [comment]
Delete system32

**Comment by NeiZeOne** [comment]
> Delete system32

rlly funny

**Comment by N-fire** [comment]
Nice you can read, maybe you can fix this error yourself.
