### ISSUE TITLE
[Bug] Keybinding?

### ISSUE THREAD

**Issue by PoorLatency** [overextended/ox_lib#132]
When testing the code below it says I pressed key `Q` when I pressed `F`. I also tried changing the keybind to `K` and it didn't seem to trigger?

```lua
local keybind = lib.addKeybind({
    name = 'respects',
    description = 'press F to pay respects',
    defaultKey = 'F',
    onPressed = function(self)
        print(('pressed %s (%s)'):format(self.currentKey, self.name))
    end,
    onReleased = function(self)
        print(('released %s (%s)'):format(self.currentKey, self.name))
    end,
})
```

**Comment by Waves966** [comment]
It seems to be a slight bug that has been reported and I'm looking into a fix

**Comment by thelindat** [comment]
I've had an empty string, `112`, and `F`. All without changing anything🙃

**Comment by thelindat** [comment]
Pretty sure this is resolved as of https://github.com/overextended/ox_lib/commit/ba635b91e7e15f14027bf56187ba26fd196ba928
