### ISSUE TITLE
[Suggestion] Info tooltip for input dialog

### ISSUE THREAD

**Issue by BerkieBb** [overextended/ox_lib#133]
![image](https://user-images.githubusercontent.com/82737367/197342608-fd5e2cd9-2b36-49ee-a412-60f7e6c6868b.png)

Like this, so you can explain what option does what and what it expects if there are certain values that are accepted.

**Comment by LukeWasTakenn** [comment]
Implemented in a6a0e4905f5ebce5112462deebd12fa5acb6f5ca
