### ISSUE TITLE
[Suggestion] Disabled Context Menu Boxes

### ISSUE THREAD

**Issue by Mkeefeus** [overextended/ox_lib#148]
QB-Menu has a disabled option that greys out a menu box and makes it not clickable, but still shows it to the player. We like to use these when we want to show a player that an option is available, but maybe they are lacking an item or similar. Would love to see this in the context menu

**Comment by Otacon-404** [comment]
the problem is that the menu box is not a button to disable it, you will have to change it from div to button so that you can disable it.

**Comment by Mkeefeus** [comment]
Ahh I see, if not that then maybe on option to change the background color or highlight color of an individual menu option. Just some way to visual distinguish an option from the others. I tried using an icon, but having one option have an icon and the others not ends up looking a little [bloated](https://cdn.discordapp.com/attachments/916754506094628995/1037827959559573535/image.png) imo

**Comment by LukeWasTakenn** [comment]
Implemented in commit 306b7b367040d50272a6ce76cf07e91316b14e57

**Comment by LukeWasTakenn** [comment]
> Ahh I see, if not that then maybe on option to change the background color or highlight color of an individual menu option. Just some way to visually distinguish an option from the others. I tried using an icon, but having one option have an icon and the others not ends up looking a little [odd](https://cdn.discordapp.com/attachments/916754506094628995/1037827959559573535/image.png) imo

I added a close button to the menu so people would stop making additional weird buttons that would close it and you add it anyways 💀
