### ISSUE TITLE
ox_lib can't find core/framework

### ISSUE THREAD

**Issue by Karlsmart7157** [overextended/ox_lib#149]
Hi my ox_doorlock won't work becasue of ox_lib can't find the framework. I have set the framework in server.cfg but it dosen't work. 
[  script:ox_doorlock] SCRIPT ERROR: @ox_lib/getCore/server.lua:44: Unable to load '@ox_lib/imports/getCore/'es_extended'/server.lua'
[  script:ox_doorlock] > fn (@ox_lib/getCore/server.lua:44)
[  script:ox_doorlock] Error loading script server/framework.lua in resource ox_doorlock: @ox_doorlock/server/framework.lua:62: attempt to index a nil value (local 'Core')
[  script:ox_doorlock] stack traceback:
[  script:ox_doorlock]  @ox_doorlock/server/framework.lua:62: in main chunk

**Comment by jaystar84** [comment]
i dont know if you fixed, but the problem is only the order of the scripts , just make sure to place all the ox scripts after the es_extended or your core
