### ISSUE TITLE
[Bug] Input Dialog: Select Labels disappear when daisy chaining dialogs

### ISSUE THREAD

**Issue by EpKouhia** [overextended/ox_lib#154]
I think I mentioned this before in dc but thought it being a fluke me using the lib. When you daisy chain multiple input dialogs to produce list based of first choice the Label disappears after the first input dialog (Gyazo attached). Adding Wait between dialogs won't change the outcome.

https://i.gyazo.com/2fa9f762b4703d1e7d268a60d6ecaad0.mp4

Lib Version: Latest Release

To Re-Produce:
```lua
RegisterCommand("bugtest", function()
    local input = lib.inputDialog('Select 1st', {
        { type = 'select', label = 'Value select #1', options = {
            {value = 'test1', label = 'Item 1'},
            {value = 'test2', label = 'Item 2'},
            {value = 'test3', label = 'Item 3'},
        }},
    })

    if input then
        local input2 = lib.inputDialog('Select 2nd', {
            { type = 'select', label = 'Value select #2', options = {
                {value = 'test1', label = 'Item 1'},
                {value = 'test2', label = 'Item 2'},
                {value = 'test3', label = 'Item 3'},
            }},
        })
    end
end)
```

**Comment by LukeWasTakenn** [comment]
Well that took me a while to debug, resolved in https://github.com/overextended/ox_lib/commit/7cde7e0581e89796b8b8127e6be309e3e0aa2e85.

As there is no unique id being passed for each row to handle rerenders, I've used the `label` for the select instead, this means if you have 2 selects back to back with the same label you'd experience the same issue again.
