### ISSUE TITLE
[SUGGESTION] notification positions

### ISSUE THREAD

**Issue by TonybynMp4** [overextended/ox_lib#156]
please add the missing left and right position 🥺

**Comment by LukeWasTakenn** [comment]
The component lib we use for the UI ([Chakra UI](https://chakra-ui.com/)) does not support center-left and center-right positions.

One idea was to patch the dep to include those positions but that means losing out on updates.

I suppose I can look into just bringing in the [toast](https://www.npmjs.com/package/@chakra-ui/toast) component separately and patching that instead. 🤷

**Comment by Scullyy** [comment]
> I suppose I can look into just bringing in the [toast](https://www.npmjs.com/package/@chakra-ui/toast) component separately and patching that instead. 🤷
Couldn't you just scrap toast and make your own notifications?

**Comment by masonschafercodes** [comment]
> Couldn't you just scrap toast and make your own notifications?

you could do this, but its a ton of extra implementation work to get something working that is remotely close to the simple hook that chakra provides.
