### ISSUE TITLE
[Suggestion] Radial Menu

### ISSUE THREAD

**Issue by Scullyy** [overextended/ox_lib#159]
One of them spinny round things you can add options to and trigger events / exports by clicking on them.

**Comment by Scullyy** [comment]
![image](https://user-images.githubusercontent.com/51968381/203240997-90f8ad91-3122-4e09-8b89-cc1426b71af9.png)
Something like this

**Comment by LukeWasTakenn** [comment]
What would you like the API for this to look like? I was thinking maybe something similar to ox_target where you add in/remove menu items and you have a canInteract function or something?

**Comment by FjamZoo** [comment]
Yeah having it like ox_target would be neat and easy to add on to resources.

**Comment by Scullyy** [comment]
> What would you like the API for this to look like? I was thinking maybe something similar to ox_target where you add in/remove menu items and you have a canInteract function or something?

Yeah that sounds good

**Comment by Oliver2911** [comment]
ko
