### ISSUE TITLE
[Bug]: Context Menus

### ISSUE THREAD

**Issue by PoorLatency** [overextended/ox_lib#161]
Since the latest update of `ox_lib` I've been receiving the error below. I will post an example code later today to reproduce it. It freezes the entire user interface, and makes you lose focus.

![Error](https://i.imgur.com/S60ZFE4.png)

**Comment by LukeWasTakenn** [comment]
Still waiting on that example code.

**Comment by Thrustgamers** [comment]
i have had the exact same issue. Here is some of the code that creates the error and problem for me

![image](https://user-images.githubusercontent.com/94409067/206001613-6afeb408-2728-4bae-beaf-3584e0769d16.png)

**Comment by LukeWasTakenn** [comment]
Code that I can easily copy and paste to quicky reproduce, not code that I have to type out and convert from qb 😭
