### ISSUE TITLE
Progress on Context does not work.

### ISSUE THREAD

**Issue by cinquina** [overextended/ox_lib#167]
![image](https://user-images.githubusercontent.com/87471252/205960425-2bc26d74-bcc7-4db0-ac84-7f38d8d9783c.png)

**Comment by cinquina** [comment]
![image](https://user-images.githubusercontent.com/87471252/205960831-53fc8a20-f885-4029-86ac-72511111bb8d.png)

**Comment by cinquina** [comment]
Im having the same problem with disabled option

**Comment by LukeWasTakenn** [comment]
Either download the source code and build the UI yourself to use it *early* or wait for the release.

Though I shouldn't have merged the docs PR until the release was out :/
