### ISSUE TITLE
Disable movement progressbar and context menu progressbar not appear

### ISSUE THREAD

**Issue by nurrifqialhusaini** [overextended/ox_lib#168]
Hello, i wanna report about disable movement not applies after new update, ped still can move when already set disable move, and i read documentation context menu we can make progressbar in context menu but the progress bar not appear..

**Comment by thelindat** [comment]
Was broken by a PR and fixed a few days ago with https://github.com/overextended/ox_lib/commit/ca38dd61ca94cf42bc8d7fcd761446d794695cf1

Was delaying the next version release for some fixes, but will be out today or within a few days.
