### ISSUE TITLE
[Feature]: Peds

### ISSUE THREAD

**Issue by PoorLatency** [overextended/ox_lib#17]
Not sure if this is the right place to request stuff like this, but it would be cool if you can add something like this to the library - https://github.com/MiddleSkillz/ms-peds or something similar.

```lua
local ped = lib.createPed(`model`, vector4(x, y, z, w), {
    invincible = true, -- boolean (optional)
    frozen = true, -- boolean (optional)
    stoic = true, -- boolean (optional)
    fade = true -- boolean (optional)
})

exports['qtarget']:AddEntityZone('pillboxDoctor', ped, {
    name = 'pillboxDoctor',
    heading = GetEntityHeading(ped),
    debugPoly = false,
}, {
    options = {
        {
            event = '',
            icon = '',
            label = '',
        },
    },

    distance = 6.0
})
```

**Comment by ohqpr** [comment]
+1, great idea & would be veru useful.

**Comment by N-fire** [comment]
Why not just spawning them server side ?

**Comment by PoorLatency** [comment]
> Why not just spawning them server side ?
I don't think qtarget works with server side exports? I might be wrong.

**Comment by BerkieBb** [comment]
qtarget is client-side only, correct

**Comment by N-fire** [comment]
That's not an issue just get the net id of the entity and then use qtarget

**Comment by dmnc14** [comment]
probably not a good idea, ms-peds is dogshit.

**Comment by thelindat** [comment]
There’s already ms peds and similar for client entities.

When I add entities to this it will be server side spawns only; the idea being to support entity lockdown.

**Comment by thelindat** [comment]
Closing this. May or may not implement 🤷‍♂️
