### ISSUE TITLE
[Suggestion] Additional modal options

### ISSUE THREAD

**Issue by PoorLatency** [overextended/ox_lib#178]
**Is your feature request related to a problem? Please describe.**
A newer version of `modal` or extended version of `alertDialog` via https://mantine.dev/core/modal/ with more customization.

**Describe the solution you'd like**
```lua
-- data: table
-- header: string
-- content: string
-- size: 'xs' or 'sm' or 'md' or 'lg' or 'xl' or `auto` (optional - default is md)
-- centered: boolean (optional)
-- overflow: boolean (optional)
-- fullscreen: boolean (optional)


local modal = lib.displayModal({
	header = "text",
	content = 'General Kenobi  \n Markdown support!',
	size = "md",
	centered = false,
	overflow = false,
})
```

**Additional context**
Let me know if my request is closed due to it being v2. I'd like to see if this is possible.

**Comment by LukeWasTakenn** [comment]
Can you clarify whether you want to see these options on just the alert dialog modal or the input dialog modal as well?

**Comment by PoorLatency** [comment]
> Can you clarify whether you want to see these options on just the alert dialog modal or the input dialog modal as well?

Your choice is fine.
