### ISSUE TITLE
onEnter triggers before another zone's onExit

### ISSUE THREAD

**Issue by mahanmoulaei** [overextended/ox_lib#179]
**Describe the bug**
I believe there is a bug with the zones. If you set up 2 zones that are **super close** to each other(they don't cross/overlap each other tho) and you go from each zone to one another, **sometimes** the new zone's onEnter is called earlier than the previous zone's onExit.

**To Reproduce**
Listening to onEnter and onExit calls by printing the interacted zone id

**Expected behavior**
Well if you are leaving a zone and entering a new one, you logically want the previous zone's onExit to be triggered prior to the new zone's onEnter _**all the time**_

**Screenshots**
![image](https://user-images.githubusercontent.com/75180223/208232212-3250e104-0326-44fe-8d34-b1bd39acea96.png)

**Comment by mahanmoulaei** [comment]
> Zones are checked on a 300ms delay, and even if that were happening at 0ms you would still trigger onEnter before onExit in the event of overlapping zones - dependent on the zone's array order.

Yes, I noticed that. I was able to sort the Zone table based on its distance attribute before updating the ```cache.coords```; it worked properly as far as I tested but the performance was horrible since ```table.sort``` was getting called every 300ms. I managed to come up with a workaround by caching an inZone variable inside the resource I am working on, but sadly that caching method has to be done in every resource that utilizes ox_lib's zones. Do you think is there any more performant method instead of ```table.sort``` that can be used within the ox_lib?

**Comment by mahanmoulaei** [comment]
> If "inZone" is intended to be the zone you are currently inside, that doesn't really make sense as you can be inside multiple zones at once.

My bad, I worded my sentence in the wrong way. =]
Let me explain the situation one more time in better wording and with a screenshot:

![image](https://user-images.githubusercontent.com/75180223/208607450-2b3d4163-eaf7-4924-8ada-7fe2bba897b8.png)
This is the workaround I came up with because sometimes ```onGymWorkoutZoneEnter``` for the new zone you're walking into gets called before the previous zone's ```onGymWorkoutZoneExit```, so it would lead to having no textUI shown if the workaround I wrote is not present in the code(none of the zones overlap/cross each other). Therefore, a similar caching method(in this case, a for-loop) has to be done in every other resource that utilizes the ox_lib's zone module.

In order to get rid of the for-loop workaround, before updating [cache.coords](https://github.com/overextended/ox_lib/blob/master/imports/zones/client.lua#L213) I sorted the [Zones ](https://github.com/overextended/ox_lib/blob/master/imports/zones/client.lua#L15)table based on its [distance attribute](https://github.com/overextended/ox_lib/blob/master/imports/zones/client.lua#L216)(which is basically the coordinates of the zone minus previous coordination of the player obtained from the previous iteration). 
The sorting snippet was something like this: 
_(I don't have the code I wrote anymore, so I'm writing a new one on GitHub without testing it based on what I remember)_
```lua
local coords = GetEntityCoords(cache.ped)
if next(Zones) then
    table.sort(Zones, function(a, b)
        -- #1
        -- if not cache.coords then cache.coords = coords end
        -- return #(a.coords - cache.coords) < #(b.coords - cache.coords)

        -- #2
        if not a.distance or not b.distance then return false end
        return a.distance < b.distance
    end)
end
cache.coords = coords
```
I put that similar block of code in [here](https://github.com/overextended/ox_lib/blob/master/imports/zones/client.lua#L211-L214), and as far as I tested it was working how it should(prev zone.onExit was getting called before new zone.onEnter **all the time**), and it allowed me to remove the for-loop workaround from my own resource but, the performance/optimization was horrible and kinda non-existence!

So, my question is do you think is there any performant method instead of ```table.sort``` that could be written directly inside ox_lib so no external workaround would be needed to fix the zones' onEnter and onExit issue that happens sometimes?

**Comment by thelindat** [comment]
Sorting zones like that just makes it so you can't remove it later, because the zone.id no longer references its position in the table (it's an ordered array).

> sometimes the new zone's onEnter is called earlier than the previous zone's onExit

You walk into zone 26 and trigger onEnter, then walk into zone 10 and trigger its onEnter; zone 26 will always trigger its functions after zone 10.

I'm pushing some changes to _maybe_ work closer to how you expect, but sorting by distance still isn't perfect; it's based on the distance to the zone's centre coordinates, rather than the nearest edge. existingZones also need to be sorted from most distant to nearest for the "best" results.

![image](https://user-images.githubusercontent.com/65407488/209421203-25356c4b-2145-490a-a8a1-0168e2c33583.png)

**Comment by mahanmoulaei** [comment]
> but sorting by distance still isn't perfect; it's based on the distance to the zone's centre coordinates, rather than the nearest edge. existingZones also need to be sorted from most distant to nearest for the "best" results.

I see your point, that is true.
Thank you for the commit. I'll go ahead and update my fork. :ox:
I'll let you know if I can find anything useful...
