### ISSUE TITLE
[Suggestion]Make exclusive item

### ISSUE THREAD

**Issue by yashatrese** [overextended/ox_lib#185]
How to make exclusive item for whitelisted job like ems "medikit" non drop or non stealable

**Comment by PickleModifications** [comment]
Technically if you use hooks you can do that.
Otherwise if you just want to prevent usage, edit the usable item registration for said item.

https://overextended.github.io/docs/ox_inventory/Functions/Server/Hooks

**Comment by yashatrese** [comment]
> I believe you meant to put this under ox_inventory.
> 
> Technically if you use hooks you can do that. Otherwise if you just want to prevent usage, edit the usable item registration for said item.
> 
> https://overextended.github.io/docs/ox_inventory/Functions/Server/Hooks

The trunk and glovebox work, but how about the drop and steal? Can you provide me a sample code please
