### ISSUE TITLE
[Suggestion] Controller Support

### ISSUE THREAD

**Issue by jxckUK** [overextended/ox_lib#198]
**Is your feature request related to a problem? Please describe.**

Not related to a problem, new feature request.

Is there any chance, to make this more accommodating for larger user bases, that we can add controller support for interface options including menu & context so that more players can use preferred input methods.

This would make it more accessible to the wide range of users that FiveM now has including players who have switched from a console device.

**Describe the solution you'd like**

The solution would allow for input of arrow keys on a DPAD to move down and up menu items similar to current functionality for up and down arrows and enter on a keyboard.

For context menus this would work when the context menu has focus and again would allow the DPAD arrows to move up and down with ENTER serving as a click.

**Additional context**

I have also requested this on ox_target but I've put here as well for the separate UX elements you provide within the library.

https://github.com/overextended/ox_target/issues/50

**Comment by LukeWasTakenn** [comment]
CEF does not support HTML's Gamepad API.
