### ISSUE TITLE
[Bug] - Zones: Script Deadloop with certain Z coordinate and debug = true

### ISSUE THREAD

**Issue by Moozdzn** [overextended/ox_lib#199]
**Describe the bug**
With debug set to true, creating a poly with certain coordinates causes FiveM to stop working with script dead loop crash

**To Reproduce**
1. Zone works as expected with the following code
```lua

    local function onEnter(self)
        print("Entered zone: " .. self.name)
    end

    local function onExit(self)
        print("onExit zone: " .. self.name)
    end

    lib.zones.poly({
        name = "undergroundcasino",
        points = {
            vec3(-118.0, 6371.0, 28.0),
            vec3(-117.0, 6372.0, 28.0),
            vec3(-121.0, 6376.0, 28.0),
            vec3(-110.0, 6386.0, 28.0),
            vec3(-117.0, 6393.0, 28.0),
            vec3(-138.0, 6370.0, 28.0),
            vec3(-134.0, 6366.0, 28.0),
        },
        thickness = 10.0,
        debug = false,
        onEnter = onEnter,
        onExit = onExit,
    })
```
2. Change debug flag to true
3. Game stops working

**Expected behavior**
The game not to crash

**Screenshots**
[Video](https://streamable.com/caclxf)

**Comment by thelindat** [comment]
@DokaDoka

**Comment by DokaDoka** [comment]
this was an interesting one, fixed in latest commits

**Comment by Moozdzn** [comment]
I tested the latest commits and it fixed the initial issue however this coordinates still produce the same deadloop crash when enabling debug

```lua
lib.zones.poly({
    points = {
        vec(1170.7375488281, 2646.0842285156, 45),
        vec(1187.0030517578, 2646.2546386719, 45),
        vec(1185.7492675781, 2635.8959960938, 45),
        vec(1170.2514648438, 2635.5, 45),
        vec(1173.3671875, 2648.8732910156, 45)
    },
    thickness = 10.0,
    --debug = true,
    name = "harmonyPoly",
})
```

**Comment by DokaDoka** [comment]
well there's your problem
![image](https://user-images.githubusercontent.com/31368547/212475789-ebc0c38c-c0a3-43df-b8ef-e6bb021eba24.png)
I'll see if I can make a detection method for that

**Comment by Moozdzn** [comment]
Damn 😅 
Im just converting them from the PolyZones resource to ox_lib and could draw it without issues. But i see what you mean and will adjust it. A warning instead of straight up crash would be nice thank you.

![image](https://user-images.githubusercontent.com/21954193/212477542-4f30d8df-8099-422b-9ac4-18b678d48084.png)
