### ISSUE TITLE
[Suggestion] Optional context search feature

### ISSUE THREAD

**Issue by Demigod916** [overextended/ox_lib#202]
In a old context menu i made i had a feature where i could optionally put a search bar at the top of the menu so i could search/filter the menu buttons based on text content they contained. 

For example if you wanted to use a context menu at a car dealership, you could type the name of the car into the search bar and it would filter down the list as you type to be able to find it more easily in the massive list of cars.

**Comment by LukeWasTakenn** [comment]
None of the menu's were designed with the idea to have a enormous amount of buttons in them in the first place, I don't really see this as something that makes a whole lot sense as for vehicle dealer resources you should really make a custom UI rather than use the context menu.

**Comment by Moozdzn** [comment]
I added a search feature to nh-context and just finished adding a search feature to ox_lib context menu. Its pretty  simple but i can make a pull request for you to take a look at.

**Comment by Demigod916** [comment]
Thats fair i guess. I can add it myself to my server, but just figured maybe others would find it useful.

**Comment by LukeWasTakenn** [comment]
If you wish to implement it yourself you can look at Moozdzn's PR (#203) but it's not something we'll be adding first party support for.
