### ISSUE TITLE
(Bug) : Not all properties of vehicles are saved

### ISSUE THREAD

**Issue by TheSpaceGamerV2** [overextended/ox_lib#21]
Hey i've got a issue with vehicle properties, when the player open the menu it's saving in a table the properties of the vehicle and when he leave a menu it's re apply the properties i saved in a table but it seems like not everything it's saved with lib.getVehicleProperties

<a href="https://cdn.discordapp.com/attachments/948516744874577940/974389017195978843/Desktop_2022.05.12_-_21.06.09.01.mp4">Preview</a>

i'm using the last version of ox_lib 

You can test that with a nero2 or lowriders vehicles, some interior "details" are not saved too but idk which :/

Repro 
```lua
RegisterCommand('setupEvery', function()
    local veh = GetVehiclePedIsIn(cache.ped, false)
    local myTest = lib.getVehicleProperties(veh)
    Wait(10000)
    print("yeh")
    lib.setVehicleProperties(veh, myTest)
end)
```

**Comment by thelindat** [comment]
Extras are set right; need to know if there are other props not saving.

**Comment by TheSpaceGamerV2** [comment]
The last commit fix my pb, thx @thelindat :heart:

**Comment by DokaDoka** [comment]
You're welcome 😉
