### ISSUE TITLE
[Suggestion] forceCancelProgressBar

### ISSUE THREAD

**Issue by SumnDaiy** [overextended/ox_lib#210]
This good but
```lua
function lib.cancelProgress()
    if not progress then
        error('No progress bar is active')
    elseif not progress.canCancel then
        error('Progress bar cannot be cancelled')
    end

    progress = false
end
```
I want this.
```lua
function lib.forceCancelProgress()
    if not progress then
        error('No progress bar is active')
    end
    progress = false
end
```

So that if something goes wrong, you can use this in an emergency?

Even if it is set to canCancel, admins can remove the progress bar from your screen.

For example, when you die and are revived, but the circle remains because it did not finish.

**Comment by thelindat** [comment]
> when you die and are revived, but the circle remains because it did not finish

Sounds like a bug, and setting progress to false won't do anything about that (the code as already executed and completed).
Even if it's a reproducible bug it doesn't matter unless occurring on v3.

cancelProgress() is already a "force cancel" anyway; though it shouldn't really bother with the canCancel check (that only matters for player input).

**Comment by SumnDaiy** [comment]
![image](https://user-images.githubusercontent.com/87270976/215064235-57d2b677-c27a-4c21-b1ee-954a62b27a10.png)
After upgrading to v3 still getting same error.

**Comment by thelindat** [comment]
You said `the circle remains because it did not finish`; I don't understand what that has to do with the progress bar not being cancel-able.

**Comment by SumnDaiy** [comment]
It didn't finish because I dont want it to finish.

I want to revive the player before the progress is done (for admin commands)

**Comment by thelindat** [comment]
You need to word your issue better, because saying "the circle remains" makes me think of an old bug where the progress bar would remain on-screen when the progress bar itself has completed.

So in short, the _only issue_ here is that a progress bar that isn't cancel-able cannot be cancelled (somewhat expected), and like I said already

> cancelProgress() is already a "force cancel" anyway; though it shouldn't really bother with the canCancel check (that only matters for player input).

**Comment by SumnDaiy** [comment]
Well, yeah my english sucks when I need to explain stuff.

I still feel like being able to cancel a progressbar via code should be achievable, even if the client shouldn't be able to cancel it

**Comment by thelindat** [comment]
> I still feel like being able to cancel a progressbar via code should be achievable, even if the client shouldn't be able to cancel it

> cancelProgress() is already a "force cancel" anyway; though it shouldn't really bother with the canCancel check (that only matters for player input).

**Comment by SumnDaiy** [comment]
I feel like im being stupid, but 

```lua
lib.progressCircle({
            duration = timer * 1000,
            label = 'unconscious',
            useWhileDead = true,
            allowRagDoll = true,
            allowCuffed = true,
            allowFalling = true,
            canCancel = false,
        })
```

I cant use lib.cancelProgress() because it can't be cancelled since canCancel is false

**Comment by thelindat** [comment]
> cancelProgress() is already a "force cancel" anyway; **_though it shouldn't really bother with the canCancel check_** (that only matters for player input).

**Comment by SumnDaiy** [comment]
Well, shouldn't but it is, so I guess this is an issue?

**Comment by mahanmoulaei** [comment]
I agree with @SumnDaiy. I've had this concern previously but I forgot to create an issue for it. The progress is only cancelable if the progress's [canCancel is not set to true](https://github.com/overextended/ox_lib/blob/master/resource/interface/client/progress.lua#L199), so basically ```lib.cancelProgress()``` does not work as a "force cancel"

**Comment by thelindat** [comment]
![image](https://user-images.githubusercontent.com/65407488/215241810-6c78efc1-886d-4d49-9e77-a2221a02b015.png)

> _**it shouldn't really bother with the canCancel check**_

https://github.com/overextended/ox_lib/commit/f9a6d8ca8ba77c75cb9742508db8f0db77170db2
