### ISSUE TITLE
FiveM crashing after adding ox_lib

### ISSUE THREAD

**Issue by kagesamo** [overextended/ox_lib#24]
Hello. I have a problem since i added ox_lib on my server. whenever I enter the server, after a few seconds the client (fivem) crashes. the error says something about NVidia GPU Drivers. if I remove the script I have no problems.

**Comment by thelindat** [comment]
I don't know what I'm supposed to do about "NVidia GPU Drivers", without being able to reproduce it, or without even the error in question.

**Comment by kagesamo** [comment]
It gives me this error anytime launch the server with ox_lib on it. If i remove ox_lib i dont have any problem.

![image](https://user-images.githubusercontent.com/28874080/170137815-f9627b54-1277-4614-af83-7b8bd87d1ee5.png)
