### ISSUE TITLE
[Bug] Barrel Problem

### ISSUE THREAD

**Issue by DyroS3** [overextended/ox_lib#248]
**Describe the bug**
when i take out the oil drum normally，when retracted again，then will generate the model

**To Reproduce**
1. take out  'WEAPON_PETROLCAN'
2. put it away

**Screenshots**
![Gif](https://user-images.githubusercontent.com/64310374/221417995-feccfdfa-4091-4752-a216-2c1dfb1aa690.gif)

**Otherthing**
Use ox_inventory version: 2.24.2
ox_lib: 2.21.0

**Comment by Scullyy** [comment]
This has nothing to do with ox_lib, open an issue on the inventory
