### ISSUE TITLE
[BUG] Progress bar

### ISSUE THREAD

**Issue by TheZahamar** [overextended/ox_lib#26]
When we have a visible progress bar and I have qtarget on the server, when we click alta, you can walk even when the option is blocked

**Comment by LukeWasTakenn** [comment]
How is this an issue with the progress bar exactly?

**Comment by TheZahamar** [comment]
If you block walking in the progress bar, and e.g. do something with this progress bar when you click ALT from qtarget you can walk

**Comment by N-fire** [comment]
so it's an issue with qtarget
