### ISSUE TITLE
Making the radialmenu close with ESC

### ISSUE THREAD

**Issue by ItzTrivial** [overextended/ox_lib#263]
**Is your feature request related to a problem? Please describe.**
No problem, just wondered that its no feature yet, since its tedious to close the radialmenu if in the 5th submenu.

**Describe the solution you'd like**
Let it close on Esc.

**Comment by Moozdzn** [comment]
You can press the keybind again to close the menu.

**Comment by ItzTrivial** [comment]
That will do the job, upsi
