### ISSUE TITLE
Images Not Being Contained Within AlertDialog [Bug] 

### ISSUE THREAD

**Issue by IamLation** [overextended/ox_lib#265]
**Describe the bug**
When an image is being displayed within the AlertDialog, it no longer contains the image as it did pre-v3. It displays the image in full resolution instead and makes it impossible to click cancel/confirm. 

**To Reproduce**
1. Create an AlertDialog.
2. Display an image in `content =`
3. Be shown that image in full resolution and not be able to click cancel/confirm buttons.

**Expected behavior**
The expected behavior would be the way it used to function previous to the v3 update - the image is neatly contained within the dialog, as seen below: 
![image](https://user-images.githubusercontent.com/59341660/223164472-ad286578-630a-4350-a3a8-a7d727513f26.png) 

**Screenshots**
When displaying an image in an AlertDialog now (post v3), it looks something like this: 
![image](https://user-images.githubusercontent.com/59341660/223164757-16f135f1-bcd4-485c-ba7f-8c49ff0373fb.png)

**Additional context**
N/A

**Comment by CrySiq** [comment]
Having the exact same issue with image, exact same oversized image that can't fit into screen
