### ISSUE TITLE
[Suggestion] Search bar option in context menu

### ISSUE THREAD

**Issue by jellyton69** [overextended/ox_lib#266]
**Is your feature request related to a problem? Please describe.**
The ability to turn on a search bar component for a context menu, which allows you to search that menu for terms in all of the different components' titles and descriptions. This is super useful for context menus that contain large amounts of components for things like choosing a paint style for a car, or if you're using the menu in which a large list of players is generated, potentially hundreds. 

**Describe the solution you'd like**
Include a option when generating a context menu that allows you to specify if a search bar should be visible in the menu, and then you can attach it to the title of the menu so it stays hoisted as you scroll.

**Comment by thelindat** [comment]
> context menus that contain large amounts of components

Not what context menu is designed for.

> like choosing a paint style for a car

Menu opening input dialog would make more sense.

> if you're using the menu in which a large list of players is generated, potentially hundreds

Again, not what it's designed for.
