### ISSUE TITLE
[Suggestion] menu_radial settings

### ISSUE THREAD

**Issue by bbeckann** [overextended/ox_lib#269]
Hello everything is fine? well, I have doubts about how I can use the radial menu, I really want to implement it in my project, I have a script that uses this radial menu. , to configure to implement a certain profession like ''qb-radialmenu'' I don't know if this is possible. but if it is not possible I would like some help on how I can implement this so that anyone can access the radial menu configured by me. Do I need to create a resource with data from 'https://overextended.github.io/docs/ox_lib/Interface/Client/radial'? If I'm talking nonsense, disregard it. thanks .
![image](https://user-images.githubusercontent.com/95275692/224495396-d1e72ca2-cfae-43a9-99d3-620e0d6e0a7c.png)

**Comment by LukeWasTakenn** [comment]
Repository Issues are not for support questions, they are for feature suggestions and bug reports.
