### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by MadManDanCat** [overextended/ox_lib#275]
**Describe the bug**
I downloaded the latest version of ox-lib and ran the script I put the ace perms in the server. Cfg but it is giving me an error.

**Screenshots**
[img]https://i.imgur.com/mGVvKfF.png[/img]

**Additional context**
I could not see anything else about installations in the git documentation.

**Comment by LukeWasTakenn** [comment]
Download the release not the source code.
