### ISSUE TITLE
[Request] 

### ISSUE THREAD

**Issue by SxIcrafter** [overextended/ox_lib#281]
**Is your feature request related to an issue? Please describe.**
I want to use ox_lib's notification system, but I can't use any of the standard color codes...

**Describe the solution you want**
Can you please add the function for the default color codes:
![image](https://user-images.githubusercontent.com/69987949/227391323-7f7af0d7-46f0-4978-b7da-5b286acb425d.png)

**Additional context**

![image](https://user-images.githubusercontent.com/69987949/227390852-035cfa2a-0972-4505-b2a9-c96824fda02d.png)

**Comment by LukeWasTakenn** [comment]
Those aren't "standard" colour codes, they are colour codes native to the GTA engine.

Not going to happen.
