### ISSUE TITLE
[Bug] color convars 

### ISSUE THREAD

**Issue by TonybynMp4** [overextended/ox_lib#283]
Putting the convars to 'orange' and 5 still gives me blue radialmenu/progressbar maybe i'm doing something wrong but i don't think so?

**Comment by LukeWasTakenn** [comment]
yes that's not how convars work.

`setr ox:primaryColor orange`

**Comment by TonybynMp4** [comment]
> yes that's not how convars work.
> 
> `setr ox:primaryColor orange`

mb assumed qbox's config was right 🤣
