### ISSUE TITLE
[Suggestion] Sound Player

### ISSUE THREAD

**Issue by marshular** [overextended/ox_lib#292]
**Is your feature request related to a problem? Please describe.**
Not an issue.

**Describe the solution you'd like**
Basically what xSound and InteractSound do, but in ox_lib.

**Additional context**
Im tired of using InteractSound and xSound.

**Comment by LukeWasTakenn** [comment]
Though a full on sound player is probably not going to happen as already dbub has a grudge against ox, perhaps there should be some sounds added for the list menu, radial menu, notifications, etc...?

Though something like that should probably be optional.

**Comment by LukeWasTakenn** [comment]
With native audio being doable now, there definitely won't be an NUI sound player.
