### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by NupNipz** [overextended/ox_lib#295]
I dont know if it is really a bug or if it is supposed to be this way but, when you start a ox_lib progressbar on a certain action it will disable the player inventory, but when you create a usable item using the QBCore CreateUsableItem function, the inventory will not be disabled

**To Reproduce**
1. Create a usable item with the QBCore CreateUsableItem Function
2. Trigger a ox_lib progressbar
3. Open your inventory

**Expected behavior**
The behavior expected is that the inventory get disabled while the progressbar is playing

**Additional context**
Like i said before if you add a progressbar in any other way, it WILL disable the inventory as long as the progressbar plays. making use of ox_inventory.

Hopefully someone could give some info on this matter, thanks!

**Comment by thelindat** [comment]
This would be inventory related rather than progressbar.. but anyway.. try removing this line.
https://github.com/overextended/ox_inventory/blob/a32c94796cc9f5659608b8eaeaa60bcb97417c43/client.lua#L361

Likely need some other tweaks if it is that.. framework item callbacks aren't really ideal/recommended.

**Comment by NupNipz** [comment]
hmm okay, i will check that out when i am home though, but if you don`t recommend the framework callbacks what do you recommend then?

**Comment by thelindat** [comment]
https://overextended.github.io/docs/ox_inventory/Guides/creatingItems/#client-callbacks

**Comment by NupNipz** [comment]
> This would be inventory related rather than progressbar.. but anyway.. try removing this line. https://github.com/overextended/ox_inventory/blob/a32c94796cc9f5659608b8eaeaa60bcb97417c43/client.lua#L361
> 
> Likely need some other tweaks if it is that.. framework item callbacks aren't really ideal/recommended.

This did indeed fix the issue, inventory will not open when the playerstate is removed, i will look into creating the items with a callback, thanks for the info!
