### ISSUE TITLE
[Suggestion] Radial menu Toggle options

### ISSUE THREAD

**Issue by ARSSANTO** [overextended/ox_lib#300]
Togglable radial menu command +openradialmenu  -openradialmenu rather static

**Comment by FjamZoo** [comment]
Just uncomment this my g
https://github.com/overextended/ox_lib/blob/master/resource/interface/client/radial.lua#L327

**Comment by ARSSANTO** [comment]
> Just uncomment this my g https://github.com/overextended/ox_lib/blob/master/resource/interface/client/radial.lua#L327

Thanks My G

**Comment by FjamZoo** [comment]
> > Just uncomment this my g https://github.com/overextended/ox_lib/blob/master/resource/interface/client/radial.lua#L327
> 
> Thanks My G

Since this is not really a suggestion and something already implemented u might wanna close the issue on github

**Comment by ARSSANTO** [comment]
yes i am about to close
