### ISSUE TITLE
[Suggestion] Add a search bar option for context / menu

### ISSUE THREAD

**Issue by 3RROR-HUB** [overextended/ox_lib#305]
I recently switched from using qb-menu to the ox_lib, and I have been thoroughly enjoying it. I would like to request the addition of a search bar option for the menu, as it would greatly enhance the user experience. Your consideration of this feature would be highly appreciated.

**Comment by LukeWasTakenn** [comment]
As previously mentioned in issues #202, #266 and #289, a search bar **will not** be added to the context menu.

**Comment by davidxd33** [comment]
This is a crime to continue denying this feature
