### ISSUE TITLE
Color Blind Command [Suggestion] 

### ISSUE THREAD

**Issue by LuckyVII777** [overextended/ox_lib#306]
add a command like /colorblind so if a server has a color said person is colorblind to it defaults to grey and white

**Comment by thelindat** [comment]
my colourblind friend's reaction to this wasn't very positive
![image](https://user-images.githubusercontent.com/65407488/236381407-5a98f79f-da17-4186-887c-25ef71c819cc.png)

I'd rather get in user customisation so it doesn't have to be an issue, but that's not going to happen anytime soon.
