### ISSUE TITLE
[Suggestion] Improve skill check scaling on higher resolutions

### ISSUE THREAD

**Issue by YoungStoner710** [overextended/ox_lib#320]
**Is your feature request related to a problem? Please describe.**

Alot of my community for my server including myself agree that the skillcheck UI could be made a little larger. Some of us are hard of seeing and get a little frustrated when we cant fully see the middle numbers to press or the line to hit a keybind on time to complete the lockpick stage.

**Describe the solution you'd like**

I would like for there to be an option to make the skillcheck UI size editable.

**Additional context**

**Comment by LukeWasTakenn** [comment]
No one has complained about the size of the skill check before and you are the only person to do so, so adding an option to set the size makes little sense to me.

Out of curiosity what res are you using?

**Comment by meltynetv2** [comment]
> No one has complained about the size of the skill check before and you are the only person to do so, so adding an option to set the size makes little sense to me.
> 
> Out of curiosity what res are you using?

I have no clue how no one else had this issue :D. I personally use 2k(2560x1440) and it is super small. like 20% bigger would be amazing! We appreciate the reply though!

**Comment by LukeWasTakenn** [comment]
Do you find any other elements to be small?

**Comment by meltynetv2** [comment]
Negative. only thing that is small is the Skillcheck. Although I have yet to try the radial menu. Otherwise the rest is perfect scaling on 2k.

**Comment by Mankeysocks** [comment]
![ui](https://github.com/overextended/ox_lib/assets/8433086/c526b33d-717d-436e-9cfa-02cefa51eec2)

**Comment by meltynetv2** [comment]
> ![ui](https://user-images.githubusercontent.com/8433086/243596737-c526b33d-717d-436e-9cfa-02cefa51eec2.PNG)

Could be a solution for some, but I personally don't like to use this setting as I use a 2k monitor, anything 1080p on a 2k monitor is pixelated imo.

**Comment by Mankeysocks** [comment]
ok well then learn Web U.i and edit the cs to be scalable fuck me

**Comment by LukeWasTakenn** [comment]
I've made some changes for 1440p in commit 241fb21.

Feedback whether these changes are enough or not would be nice.

**Comment by meltynetv2** [comment]
> I've made some changes for 1440p in commit [241fb21](https://github.com/overextended/ox_lib/commit/241fb2107bc3ad7064e9b1391fc4c8e01b389f54).
> 
> Feedback whether these changes are enough or not would be nice.

I will check this today and let you know!

**Comment by meltynetv2** [comment]
> I've made some changes for 1440p in commit [241fb21](https://github.com/overextended/ox_lib/commit/241fb2107bc3ad7064e9b1391fc4c8e01b389f54).
> 
> Feedback whether these changes are enough or not would be nice.

Hey, sorry to bother, is this included in the latest build? As I can not build it myself.

**Comment by LukeWasTakenn** [comment]
It's not, hence I want feedback
