### ISSUE TITLE
Notifications style color only affects title, not description

### ISSUE THREAD

**Issue by IamLation** [overextended/ox_lib#324]
**Describe the bug**
As the title states it seems that the notifications style table color option only affects the title text color and not the description text color. I've tested this on all notification types, etc. I am also on the latest ox_lib release. You can set "backgroundColor" and "color" however "color" only affects the title, and not the description. 

**To Reproduce**
1. Go to a notification you can edit
2. Add the style table and set a custom color option
4. See that only the title text color was adjusted and not the description text color

**Expected behavior**
If I remember correctly when adjusting the color option in the past it would affect both title & description and I was expecting that to be the case when I started messing with this. 

**Screenshots**
![FiveM_b2699_GTAProcess_2023-05-09_15-55-13](https://github.com/overextended/ox_lib/assets/59341660/e22fc290-49db-4219-b420-3246f42cfaa5)

**Additional context**
It would be nice when adding custom styling options to notifications that it would adjust all the text color. Because without it it just won't look right. Let's say I wanted success and error types to look like this:

![FiveM_b2699_GTAProcess_2023-05-09_15-59-51](https://github.com/overextended/ox_lib/assets/59341660/1030105d-af07-4240-a4f5-14fdab00f5db)

![FiveM_b2699_GTAProcess_2023-05-09_16-00-48](https://github.com/overextended/ox_lib/assets/59341660/e6ffaa43-3bbf-4283-8861-982e5a27622a)

I can't :( because the description text just remains the default color and looks bad or unreadable depending on the background color you are using. If this is intentional, my apologies. Furthermore if I'm doing something wrong here - I apologize haha.

**Comment by LukeWasTakenn** [comment]
This is not a bug, `style` only applies the styling to the container element of the notification.

I've added a class to the description and changed the styling to go trough the Sx prop instead of html's style (2199079).

Which means you can now target the description class like so:

```lua
lib.notify({
    id = 'some_identifier',
    title = 'Notification title',
    description = 'Notification description',
    position = 'top',
    style = {
        backgroundColor = '#141517',
        color = '#909296',
        '.description' = {
            color = 'red'
        }
    },
    icon = 'ban',
    iconColor = '#C53030'
})
```
