### ISSUE TITLE
[Suggestion] Radial Customization

### ISSUE THREAD

**Issue by Virus18sp** [overextended/ox_lib#326]
Ability to change colors, size, padding, etc to Radial like the Notifications so users can match there server theme colors.

**Comment by LukeWasTakenn** [comment]
use the `ox:primaryColor` and `ox:primaryShade` convars.

<https://overextended.github.io/docs/ox_lib/Interface/>

If you need anything more than that then you are going to have to edit the source code.

**Comment by Virus18sp** [comment]
> use the `ox:primaryColor` and `ox:primaryShade` convars.
> 
> https://overextended.github.io/docs/ox_lib/Interface/
> 
> If you need anything more than that then you are going to have to edit the source code.

Got it, didnt see that. Thanks.
