### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by NathanT200** [overextended/ox_lib#344]
local input = lib.inputDialog('Dialog title', {
  {type = 'input', allowCancel = false, label = 'Text input', description = 'Some input description', required = true, password = true, min = 4, max = 16},
})
this is my inputDialog but i want to make it so players can't Cancel but when i put allowCancel it doesn't work

**Comment by mikigoalie** [comment]
![image](https://github.com/overextended/ox_lib/assets/22800996/a7f8b5e4-2e2c-43fc-8714-805e6f61b727)


?

**Comment by NathanT200** [comment]
yeah but I don't understand where to put the allowcancel = false

**Comment by daZepelin** [comment]
You are adding the `allowCancel` to the input row, when it has to be added as an option which is the third parameter to `inputDialog` function
![image](https://github.com/overextended/ox_lib/assets/63473480/6b40b44b-edde-4184-a4d4-c44440f1f3b2)


It should look somewhat like that:
```lua
local input = lib.inputDialog('Dialog title', {
    {type = 'input', label = 'Text input', description = 'Some input description', required = true, password = true, min = 4, max = 16},
}, {allowCancel = false})
```
