### ISSUE TITLE
[Suggestion] In zones checks

### ISSUE THREAD

**Issue by czsquizer** [overextended/ox_lib#349]
It would be cool to have the possibility to check if a player/coord is in poly/box zone or not. Now there are only functions called when we are in/we leave/enter but we can not check if a point is in:

It could look like this

```lua
local` box = lib.zones.box({
    coords = vec3(442.5363, -1017.666, 28.65637),
    size = vec3(1, 1, 1),
    rotation = 45,
    debug = true,
    inside = inside,
    onEnter = onEnter,
    onExit = onExit
})

box:isCoordInside(vec3(158.4, 4558.2, 4556.0))
``` 
And it would return true it the point is inside or false when it is not.

Also grouping box zones into 1 would be fine, so we could check if player is in any zone or not. Like the old PolyZone script did.

**Comment by jag3dagster** [comment]
Docs are just out of date: https://github.com/overextended/ox_lib/blob/master/imports/zones/client.lua#L8

**Comment by thelindat** [comment]
We're using the glm library, so you have access to dozens of different methods for polygons.
https://github.com/citizenfx/lua/blob/luaglm-dev/cfx/EXTENDED.md#polygon

```lua
local box = lib.zones.box({
    coords = vec3(442.5363, -1017.666, 28.65637),
    size = vec3(1, 1, 1),
    rotation = 45,
    debug = true,
})

print(box.polygon, box.polygon:area(), box.polygon:centroid())
```

Otherwise as jag mentioned, docs are just missing information.

```lua
print(box:contains(vec3))
```
