### ISSUE TITLE
[Suggestion] Dialog / Popup (Interface)

### ISSUE THREAD

**Issue by PoorLatency** [overextended/ox_lib#35]
Is it possible to get https://chakra-ui.com/docs/components/overlay/alert-dialog#changing-the-transition as a dialog for an example. You want a prompt for the person to read text/close it manually? For an example, you want to provide a list of something to someone.

```lua
lib.registerDialog({
    id = 'popup_example',
    title = 'Ingredients: McMuffin',
    description = '1. Egg\n2. Bread\n3. Peanut Butter'
})

lib.showDialog('popup_example')
```

**Comment by waddle1010** [comment]
+1

**Comment by LukeWasTakenn** [comment]
This is now a feature as of commit 186014f95ece0700baf85078df087d5fd2f78805

Usage and examples will be documented when a new tag is pushed.
