### ISSUE TITLE
[Bug] Unable to open menu

### ISSUE THREAD

**Issue by TankinTom** [overextended/ox_lib#354]
When opening a menu, I get a cursor, and nothing else, the Error console shows this error however, and it started completely at random.

cannot read properties of null (reading 'disabled')
![20230612223819_1](https://github.com/overextended/ox_lib/assets/90729413/067da0b9-ef63-4a26-88d5-07dd3f759217)

What its doing is I'm trying to access the evidence database for Wasabi_evidence. It was working fine up until the other day. I also have a ticket open with them. It's not happening to any other menu other than this one.

**Comment by LukeWasTakenn** [comment]
Probably improper usage.
