### ISSUE TITLE
[Bug] progressBar trigger is not normal

### ISSUE THREAD

**Issue by DyroS3** [overextended/ox_lib#355]
**Describe the bug**
I made two short videos, one is normal and the other is abnormal

**Screenshots**
[this normal](https://streamable.com/2yd2f9)
[not normal](https://streamable.com/ulyil0)

**Additional context**
this is my codes
```lua
function Healing()
    lib.progressBar({
        duration = Config.ReviveTime,
        label = '正在治疗中...',
        useWhileDead = true,
        canCancel = false,
        disable = {
            move = true,
        },

    }) 
    TriggerEvent('esx_ambulancejob:revive')
    Notify("您的治疗已完成，您已被收取费用: "..Config.Price)
    TriggerServerEvent('Shuguang:charge')
end
```

**Comment by thelindat** [comment]
Isn't this because you're falling at the time progressbar is called?
You'll want `allowRagdoll` and `allowFalling`.

**Comment by DyroS3** [comment]
> Isn't this because you're falling at the time progressbar is called? You'll want `allowRagdoll` and `allowFalling`.

got it ,thx
