### ISSUE TITLE
[Enhancement] Reflect dialog box changes in a function before confirming

### ISSUE THREAD

**Issue by mahanmoulaei** [overextended/ox_lib#356]
**Is your feature request related to a problem? Please describe.**
It would be nice to reflect the dialog box input changes through some sort of `onSelect/onChange` function for each entry; something like the menu's `onSelected(), onSideScroll(), & onCheck()` functions.

**Describe the solution you'd like**
Being able to know what input is entered in each dialog box entry before actually confirming the menu, so based on that, we could modify other entries' values or behavior. Something with a [similar use case of being able to modify other entry's attributes such as checked, required, default, disabled, etc...](https://github.com/overextended/ox_lib/issues/279) on interacting with a specific input

**Additional context**
- As an example, setting an entry's check box to `true` once another entry's input value is above 1.0, or disabling a certain input once a specific check box is set `true` and vice-versa...
- Or as another example, setting the rain level's default value to `0.5` when `RAIN` is chosen, or setting it to `1.0` when `THUNDER` is chosen before confirming the menu or manually setting the rain level in the below menu: 
![image](https://github.com/overextended/ox_lib/assets/75180223/a9cfe904-760c-41af-9d1b-ba0578700a5b) ![image](https://github.com/overextended/ox_lib/assets/75180223/10b01f0a-faf3-4307-95f8-4ba73e16c4cd)

**Comment by LukeWasTakenn** [comment]
Input dialog is supposed to be a form, it has no state and everything is validated upon submit so I don't really think this is something that would be fitting and would probably lead to more bloat but I'm open to the discussion.

**Comment by mahanmoulaei** [comment]
Come on Luke, the bloat is part of the fun and charm, it's for the community.

But seriously, I feel like it can open up opportunities to have nice interactive-rich forms. The range of use cases is vast and of course, it makes the usage of the form more professional by being able to modify its entry properties before validating as I mentioned before, but ultimately the choice is really up to you.
