### ISSUE TITLE
[Bug] InputDialog type:number min,max

### ISSUE THREAD

**Issue by morpheus1076** [overextended/ox_lib#359]
**Describe the bug**
Defination type 'number' , min=0, max=10

When input > max and pressing ENTER it takes the input(e.g. 20) not the max.
Its only when pressing ENTER, use the Interfacebutton everything is O.K.

**To Reproduce**
1. Input = 20 "press Enter" takes 20, and not the max value
2. Input = 30 "hit Interface Button" and it takes the max (this ist OK)

**Expected behavior**
if input "pressing ENTER" >max then max
or
if press ENTER, force interfacebuttom

**Screenshots**
No

**Additional context**
Thanks to all of you for your very good work.

**Comment by LukeWasTakenn** [comment]
Seems to be happening because pressing enter will not unfocus from the input causing it to not change state to the max value, while going over to the confirm button does.

**Comment by morpheus1076** [comment]
Yes, thats it. Maybe all types with min/max have same bug. By using type slider, you can´t go over max.

**Comment by LukeWasTakenn** [comment]
Should be resolved with 45e9588.

Rather than letting you submit the form and send through the unclamped value, now instead when trying to submit nothing will happen, which arguably isn't great ux but it's probably better than unintentionally sending in values you're not supposed to.
