### ISSUE TITLE
[Suggestion] Sound can be added for ox_lib notifications

### ISSUE THREAD

**Issue by RAXIC7** [overextended/ox_lib#362]
Sound can be added for ox_lib notifications if possible 

Example:  
**lib.notify({title = 'Info', description = 'my text.', position = 'top', duration = 5000, sound = 'sounds/info.mp3', type = 'success'})**

There will be a folder named **sounds** and we will put the sounds we want in that folder.
Then, in the code above, we can write the name of the sound we want to use from the sound section and use it.

It would be great if what I wrote could be done because the notifications look very ordinary, at least if sound is added, it can add an air to the notifications.

**Comment by LukeWasTakenn** [comment]
If this is to be done, it would probably use native audio rather than audio from NUI.
