### ISSUE TITLE
Make colorScheme for metadata in Context menu [Suggestion] 

### ISSUE THREAD

**Issue by bohous04** [overextended/ox_lib#367]
Make option to make proggres bar in metadat colorful. Thanks :D

**Comment by LukeWasTakenn** [comment]
setting `colorScheme` on the button already works.

**Comment by bohous04** [comment]
On button yes, but not in metadata

**Comment by LukeWasTakenn** [comment]
![image](https://github.com/overextended/ox_lib/assets/39926192/bf2a763f-fb95-495d-91a9-581f06789492)
![image](https://github.com/overextended/ox_lib/assets/39926192/eba2abbf-5d36-4491-8a35-92c68ba98bd4)
