### ISSUE TITLE
Context Menu Button Title "." [Bug] 

### ISSUE THREAD

**Issue by Kaanhehe** [overextended/ox_lib#373]
**Describe the bug**
If you add a dot (".") somewhere in the title of a button in the context menu the buttons gets really big

**To Reproduce**
1. Try adding a context menu with button
2. Put a dot in the title of the button
3. See error

**Expected behavior**
the button staying the same size

**Screenshots**
![image](https://github.com/overextended/ox_lib/assets/81617346/aa620a95-f378-40c9-bd1d-f4948db5032d)
![image](https://github.com/overextended/ox_lib/assets/81617346/9f98bc31-97a1-40e9-85f0-b65a5aa58a4e)

**Additional context**
////

**Comment by Kaanhehe** [comment]
i found out that this error only accourse if you use a not negative number followed by a dot, so if you set a letter after the dot (1.A) this does not happen anymore its only if you have "NUMBER+."

**Comment by LukeWasTakenn** [comment]
This is not a bug. It's feature of markdown.

To go around this you can use an invisible 0 space width character like `&#8291;`

```lua
title = '&#8291;1. First button'
```
