### ISSUE TITLE
[Bug] skillcheck options bug - easy by pass

### ISSUE THREAD

**Issue by reeeum** [overextended/ox_lib#376]
**Describe the bug**
All options can be pressed on the skill check for an easy bypass.

**To Reproduce**
Use any Skill check on anything. But apply several keys. Example:

lib.skillCheck({'easy', 'easy', 'easy'}, {'1','2','3'})

Pressing 1,2 and 3 all together at the same time will result in a passed skill check.

**Expected behavior**
Other numbers pressed should equal fail.

**Screenshots**
N/A

**Additional context**
Probs make it a single input only?

**Comment by LukeWasTakenn** [comment]
I've implemented some  in commit 5b9bb53 logic to fail the user if they press the wrong key at any point during the skillcheck which should hopefully resolve this issue.

Can you build the source code and give it a try to see if it still occurs?

**Comment by reeeum** [comment]
> I've implemented some in commit [5b9bb53](https://github.com/overextended/ox_lib/commit/5b9bb531a94bcb9a1c403dddf18997b48f2f4a1c) logic to fail the user if they press the wrong key at any point during the skillcheck which should hopefully resolve this issue.
> 
> Can you build the source code and give it a try to see if it still occurs?

I shall test! Thanks for the reply

**Comment by LukeWasTakenn** [comment]
Any updates on this?

**Comment by reeeum** [comment]
Apologies not had the time to test this one... 

This still on going?

**Comment by LukeWasTakenn** [comment]
Cool guess I'll just assume the issue is fixed.
