### ISSUE TITLE
[Bug] context menu - onExit

### ISSUE THREAD

**Issue by benzon** [overextended/ox_lib#38]
Hey,

Used the example code to test this out multiple times, the onExit event dos not seem to fire when pressing ESC to exit the menu.

Should be easy to replicate, use the example code from documentation, it wont return a print in console, when closing the menu.

**Comment by LukeWasTakenn** [comment]
We haven't pushed a tag with the onExit feature yet, if you wish to use now you'd have to download the source code and build the UI yourself.

I need to stop pushing docs for features that we haven't pushed a tag for yet lol

**Comment by benzon** [comment]
@LukeWasTakenn it's in the documentation tho haha :P that might be a bit confusing.
