### ISSUE TITLE
[Bug] Cron not working overnight

### ISSUE THREAD

**Issue by TomStilson** [overextended/ox_lib#384]
**Describe the bug**
If a Cron task is created within a day and the task runs after midnight to the next day, the task does not execute and will not executed the next day. The scheduled run at 00:00 also does not work.

**To Reproduce**
1. Create a Cron task like the following:
```lua
local paydayTask = lib.cron.new("0 * * * *", function()
    -- payday code that will run every hour.
end)
```
2. Wait until the midnight of the following day.
3. The task will not run at midnight and will not resume functioning in the next day.

**Expected behavior**
The Cron task will run smoothly.

**Screenshots**
N/A

**Additional context**
We have checked the server console but no error messages were printed. We only tried the pattern `0 * * * *`.

**Comment by thelindat** [comment]
Recent cron tweaks broke this I guess?

**Comment by TomStilson** [comment]
> Recent cron tweaks broke this I guess?

Yes I think so. It used to be working before the update 3.7.0.

**Comment by thelindat** [comment]
https://github.com/overextended/ox_lib/commit/45362017c6695afddb04bd64f7152daf2d49cc80 should resolve it, hopefully without other regressions.

**Comment by TomStilson** [comment]
> [4536201](https://github.com/overextended/ox_lib/commit/45362017c6695afddb04bd64f7152daf2d49cc80) should resolve it, hopefully without other regressions.

Thank you! I will try it now and provide more information tmr.

**Comment by TomStilson** [comment]
> [4536201](https://github.com/overextended/ox_lib/commit/45362017c6695afddb04bd64f7152daf2d49cc80) should resolve it, hopefully without other regressions.

We have tested the updated cron script and everything works perfectly now.
