### ISSUE TITLE
[Bug] All about request stream (3.8.0)

### ISSUE THREAD

**Issue by nurrifqialhusaini** [overextended/ox_lib#386]
Hello, actually this bug has been around for quite a while, where is the worst impact on requestModel(). When the player logs out of the game in the shell/near npc ped (whatever model it is). When logged in again, the model will fail to load.

Preview : https://discord.com/channels/813030955598086174/1136385394246680716

**Comment by thelindat** [comment]
Would be useful to see the full code.

**Comment by nurrifqialhusaini** [comment]
Wait, ill send full code in discord

**Comment by nurrifqialhusaini** [comment]
![image](https://github.com/overextended/ox_lib/assets/60453612/649fd137-c0a6-46c0-8982-0fa6326f2ead)

**Comment by thelindat** [comment]
1. You've set a very short timeout.
2. Clear the models and anim dicts once you're done with them (https://docs.fivem.net/natives/?_0xE532F5D78798DAAB https://docs.fivem.net/natives/?_0xF66A602F829E2A06).

**Comment by nurrifqialhusaini** [comment]
wait, ill try

**Comment by nurrifqialhusaini** [comment]
This experiment 1 with 500
![image](https://github.com/overextended/ox_lib/assets/60453612/43f565af-c10c-49e9-9765-0bfb7fc29870)
![image](https://github.com/overextended/ox_lib/assets/60453612/8e9779a7-c570-4814-8bf2-04562469cfac)

But after change 1500, its work fine.
![image](https://github.com/overextended/ox_lib/assets/60453612/a245e61e-2363-47af-8db6-b9a743adba15)
![image](https://github.com/overextended/ox_lib/assets/60453612/c9cdae5f-31ca-4472-b7e8-03e5b6461eca)

I haven't tried to shell model, but solved this time is add more the timeout.

**Comment by nurrifqialhusaini** [comment]
Thank you @thelindat
