### ISSUE TITLE
[Suggestion] Wait for the NUI to be ready when calling UI functions

### ISSUE THREAD

**Issue by draobrehtom** [overextended/ox_lib#389]
**Description**
When connecting to the server and instantly calling lib.notify, the notification is not displayed.

**Describe the solution you'd like**
Wait for the NUI to be ready when calling UI functions. 
```lua
local isNuiReady = false
RegisterNUICallback('nuiReady', function(_, cb)
    isNuiReady = true
end)

local function waitForNui()
    while not isNuiReady do 
        Wait(0) 
    end
end

function lib.notify(...)
    waitForNui()
    -- ...
end
```

**Comment by thelindat** [comment]
> instantly calling lib.notify

seems unnecessary?

**Comment by draobrehtom** [comment]
There can be some cases when game requires notification or other UI at the very beginning, however it can be tricky to manage this (using `Wait` is a one workaround for this, however you can't be sure for how much to wait).

**Comment by jellyton69** [comment]
Can you check yourself using your own NUI Callback? It seems to me that NUI loads all UI on the server at the same time.

**Comment by draobrehtom** [comment]
> Can you check yourself using your own NUI Callback? It seems to me that NUI loads all UI on the server at the same time.

Not sure if it is possible without editing ox_lib.

**Comment by draobrehtom** [comment]
> Can you check yourself using your own NUI Callback? It seems to me that NUI loads all UI on the server at the same time.

I've just checked the solution, and it worked. Thank you for suggesting this solution!
