### ISSUE TITLE
[Bug] module 'glm' not found

### ISSUE THREAD

**Issue by zf-development** [overextended/ox_lib#397]
**Describe the bug**
When trying to make zones in the last ox_lib version **(3.8.1)**, there is this error:
![image](https://github.com/overextended/ox_lib/assets/48424078/051624ec-7ee4-4ddf-9fa8-3845f765be99)

**To Reproduce**
Install last ox_lib version.
Try this code:
```lua
lib.zones.box({
    coords = vector3(-221.13, -1163.09, 22.87),
    size = vector3(7.5, 7.5, 7.5),
    rotation = 0,
    onEnter = function()
        print('entered zone')
    end
})
```

**Expected behavior**
This will happen and zone will not be created.
![image](https://github.com/overextended/ox_lib/assets/48424078/051624ec-7ee4-4ddf-9fa8-3845f765be99)

**Screenshots**
![image](https://github.com/overextended/ox_lib/assets/48424078/051624ec-7ee4-4ddf-9fa8-3845f765be99)

**Additional context**
**OX Lib Version**: 3.8.1
**FiveM Server Artifact**: 6594
**Gamebuild Version**: 2944
**Onesync**: On (with Infinity)

**Comment by zf-development** [comment]
And yes ox_lib is started before. (just making sure I'm not asked this question)

**Comment by thelindat** [comment]
That doesn't even make sense as glm is built-in/packaged with FiveM/FXServer. It needs 5.4 to use, but ox_lib already enforces that.

**Comment by zf-development** [comment]
I know.. I have lua54 enforced in my manifest also but it tells me this error...

**Comment by thelindat** [comment]
Make this change to `imports/require/shared.lua` and let me know the output. If it says the same thing I really don't know what to do, as it's unrelated to ox_lib (using the standard require function).
```lua
        if modname == 'glm' then
            return error(result, 2)
        end
```
![image](https://github.com/overextended/ox_lib/assets/65407488/883fc44a-38f0-4006-ae9c-4bb46ee42269)

**Comment by zf-development** [comment]
It's good... I'm sorry it was not ox_lib but that did shit...
Sorry for disturbing

**Comment by thelindat** [comment]
> but that did shit...

Eh? That code I asked you to add doesn't fix anything I just want to know the output; it should be removed or require won't work.
glm should be getting loaded by _require and set before that error can even throw.

**Comment by zf-development** [comment]
I did shit **
I had a function named require in my script.. It was causing error with the require of ox_lib. the code you sent me is not in ox_lib and it's working now I just changed my function name. 
I haven't thought about the require function in my script :|
