### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Blackmagic675** [overextended/ox_lib#398]
**Describe the bug**
When ox_lib starts it prints all the permissions into the console is this an issue?

**Screenshots**

![Screenshot_7](https://github.com/overextended/ox_lib/assets/26082115/f686ddd5-9aac-4c63-8517-90a10df6e98d)

**Comment by thelindat** [comment]
no it doesn't

**Comment by Blackmagic675** [comment]
I've been threw each resource and started them individually and ox_lib is the only one that dose this. If it's not ox_lib any idea what may be causing this?
