### ISSUE TITLE
[Bug] Cannot change extras if set by lib.setVehicleProperties

### ISSUE THREAD

**Issue by xDope7137** [overextended/ox_lib#399]
**Describe the bug**
When you set a vehicles properties using lib.setVehicleProperties, you cannot use "SetVehicleExtra" natives to add a extra. You can remove a extra, but cannot add one.

**To Reproduce**
1. Set a vehicles properies using setVehicleProperties function
2. Try to set a vehicles extra using SetVehicleExtra(vehicle, tonumber(id), 0)
3. The vehicle will not visually gain a extra, but removing a extra will work
4. Try removing "SetVehicleAutoRepairDisabled(vehicle, true)" from lib.setVehicleProperties function and repeat the steps. It will work fine.

**Expected behavior**
It works if you remove "SetVehicleAutoRepairDisabled(vehicle, true)" native from the function.

**Comment by thelindat** [comment]
https://docs.fivem.net/natives/?_0x115722B1B9C14C1C

**Comment by xDope7137** [comment]
thank you for fixing it finally :))
