### ISSUE TITLE
[Bug] lib.callback.await

### ISSUE THREAD

**Issue by benzon** [overextended/ox_lib#40]
Hey,

lib.callback.await dos not return a result after the lates version upgrade.

**Comment by thelindat** [comment]
I almost exclusively use await and it works fine. If you haven't restarted ox_lib and whatever is using it since updating, then it's probably loading the old functions.

**Comment by benzon** [comment]
i did restart thats the thing.

And it's a rather simple callback to be honest.

**Server**
```
lib.callback.register('drp_storagev2:server:fetch:data', function(source)
    return Config
end)
```

**Client**
```
local data = lib.callback.await('drp_storagev2:server:fetch:data', false)
```

**Comment by benzon** [comment]
Double checked re-downloaded, restartet the server fully, it's not returning a result.

**Comment by benzon** [comment]
hmm ill test once more.

all im doing is sending over a static array.

**Comment by benzon** [comment]
![image](https://user-images.githubusercontent.com/3528000/174444826-ff607d30-3feb-4fec-adc0-701b2e2eec0f.png)

![image](https://user-images.githubusercontent.com/3528000/174444804-7be556df-e595-4d39-9367-66d7982af6bc.png)

**Comment by thelindat** [comment]
That's cool, but we're using the same lib and you're the only one reporting an issue; not sure what you want me to do for you.

**Comment by benzon** [comment]
But you got to agree with me it's kinda wird, it works for you and not me, since a basic fetch resource should return something, insted of just being idc, dont wanna reply.

**Comment by benzon** [comment]
Basically, m just trying to figure out why this happens, why it refuses to return data, for any callbacks in 2.5 vs the 2.4 release.

And trying to figure out how to solve this and finding a solution to the issue im facing currently.

**Comment by benzon** [comment]
Okay this just got very very wird, very quickly, just did a fully new resource, data returns.

But the script that works with 2.4 stil dos not work with 2.5 so it gotta be some edge case dafuq.

**Comment by benzon** [comment]
Aha, had an array called cache = {} the changes in 2.5 made it sensitive to this good to know :D
