### ISSUE TITLE
[Suggestion] Delete/remove Context Menu

### ISSUE THREAD

**Issue by niklasnsdev** [overextended/ox_lib#400]
**Is your feature request related to a problem? Please describe.**
it would be good if you add this function

**Describe the solution you'd like**
Example:
function lib.deleteContextMenu(data)
    if not data.id then error('No menu id was provided.') end
    if not registeredMenus[data.id] then return end
    table.remove(registeredMenus, data.id)
end

**Additional context**
N/A

**Comment by LukeWasTakenn** [comment]
What's the use case...?
