### ISSUE TITLE
No such export cache

### ISSUE THREAD

**Issue by maejok-xx** [overextended/ox_lib#403]
**Describe the bug**
Getting "@ox_lib/init.lua:171: No such export cache in resource ox_lib" for every resource that uses ox_lib

**To Reproduce**
1. install ox_lib as directed in docs
2. run server

**Expected behavior**

**Screenshots**
![image](https://github.com/overextended/ox_lib/assets/12991886/d85e2471-14ca-4d35-a9d3-4cd32cb1d306)

**Additional context**
Operating System: Debian GNU/Linux 12 (bookworm)
Kernel: Linux 6.1.0-11-amd64

**Comment by maejok-xx** [comment]
cloned to a win32 box everything works fine

**Comment by maejok-xx** [comment]
no server errors, client only

**Comment by DokaDoka** [comment]
you have /cache in a .gitignore somewhere

**Comment by maejok-xx** [comment]
That worked, thank you!

Would you mind clearing something up for me?  It makes no sense to me why that was the cause.  Cache is generated by both the linux and windows servers, so why did the linux server need the windows generated cache?

**Comment by thelindat** [comment]
> It makes no sense to me why that was the cause.

Because globally blocking any folder or file named cache blocks _any folder or file named cache_. ox_lib contains cache folders, you need those to run it.

**Comment by maejok-xx** [comment]
That makes sense! Thanks!

**Comment by xhorntail** [comment]
Hrm.. That's an unfortunate conflict with CFX conventions.
For anyone else coming here and still desiring to .gitignore the FXA cache, one would do so with something like the following:
```gitignore
cache/
!resources/**/cache
```

You may want to get more explicit with the exclude, depending what caching operations you have running in your resources path.
