### ISSUE TITLE
[Suggestion] showTextUI over multiple lines

### ISSUE THREAD

**Issue by Spudgun** [overextended/ox_lib#406]
**Is your feature request related to a problem? Please describe.**
Not a problem, but it would be a nice feature to have the lib.showTextUI be able to spread over multiple lines. You can currently achieve this for one line by using the `\n` new line but unfortunately not for multiple lines.

**Describe the solution you'd like**
![image](https://github.com/overextended/ox_lib/assets/3261320/d429c3eb-fc37-449a-9817-b09826718954)

**Additional context**
**_With one `\n`_**
![image](https://github.com/overextended/ox_lib/assets/3261320/456e04e5-e7cf-4743-a9ac-7a854818373d)
![image](https://github.com/overextended/ox_lib/assets/3261320/a559a755-05c2-4feb-ae58-ae350b14f096)

**_With two `\n`_**
![image](https://github.com/overextended/ox_lib/assets/3261320/20565133-ef20-4235-86cf-7ca77f021668)
![image](https://github.com/overextended/ox_lib/assets/3261320/45f3a2d0-3055-4b77-aae4-b9dfe7434b05)

**Comment by DokaDoka** [comment]
`  \n` two spaces

**Comment by Spudgun** [comment]
Unfortunately this does not work

**Code**
`
lib.showTextUI("**Safe Cracking**  \n[L Shift] Halfspeed\n\n[←] & [→] Rotate\n\n\n[ESC] Cancel", {
    position = "top-center",
    icon = 'vault',
})
`

**Context**
![image](https://github.com/overextended/ox_lib/assets/3261320/bddb8f65-1f36-4a6e-b01b-387796c729d1)
