### ISSUE TITLE
[Suggestion] showTextUI position

### ISSUE THREAD

**Issue by Spudgun** [overextended/ox_lib#408]
**Is your feature request related to a problem? Please describe.**
Create a few more position attributes that can be applied. I feel like just having more options to position the showTextUI would be beneficial.

**Describe the solution you'd like**
I would love if the following positions would also work with showTextUI:

`left-top`
`right-top`

`center-mid`

`left-bot`
`center-bot`
`right-bot`

**Additional context**
It also might be worthwhile changing the naming conventions of the already existing positions to:

`right-center` -> `right-mid`
`left-center` -> `left-mid`
`top-center` -> `middle-top`

**Comment by LukeWasTakenn** [comment]
> It also might be worthwhile changing the naming conventions of the already existing positions to:

That breaks compatibility.

Text UI is supposed to be easily seen and I don't think putting it in the corners helps that as it's a bit more important than notifications, but I'm open to the discussion.
