### ISSUE TITLE
[Bug] Non-english keyboards don't register key presses properly

### ISSUE THREAD

**Issue by RosenIgn** [overextended/ox_lib#410]
Most of our players are having a big issue with the lib.skillCheck everywhere(in jobs, vehicle keys, and much more). The problem happens quite often with different players, but when they delete the mash it gets better for a while.

**Expected behavior**
The problem is the following: The skill bar appears and when it is already in the area, they press the button and it says that they failed (it is not included in the success check). I am attaching a video to show you exactly what the problem is.

**PREVIEW**
https://streamable.com/ymby82

**Comment by LukeWasTakenn** [comment]
Any code? I can't reproduce this at all and seems like no one else reported anything similar.

**Comment by RosenIgn** [comment]
> Any code? I can't reproduce this at all and seems like no one else reported anything similar.

The issue is happening at random times. Sometimes it works, sometimes it doesn't work. After a player relogs, the issue is getting fixed for a while. Here is some code:

            local success = lib.skillCheck({'easy', 'easy', {areaSize = 70, speedMultiplier = 1.50}, 'easy'}, {'w', 'a', 's', 'd'})
            if success then
                ClearPedTasks(playerPed)
                SetVehicleEngineHealth(car, 1000.0)
                SetVehicleFixed(car)
                SetVehicleDeformationFixed(car)
                TriggerServerEvent("jd-mechanicjob:server:GiveItems")
            end
            
            
 This code is a normal event in our mechanic job. The issue is happening in lockpicking vehicles, fishing, electrician job, and much more.

**Comment by LukeWasTakenn** [comment]
Can't reproduce this at all and as I've said no one else has reported this issue still so I'm not sure what's going on.

**Comment by RosenIgn** [comment]
That's strange, yes. We are just receiving tickets and tickets for this issue from our players. For example, I have never had this issue but some of our staff members have it. One of the players sent this screenshot in F8 and just wondered if the issue can be from this but I don't think so. What do you think?

Screenshot: https://i.imgur.com/alYMBsH.png

**Comment by LukeWasTakenn** [comment]
You could have something taking over NUI focus or something causing the key press to not register correctly - which would be the most likely case since no one reported this issue still...?

Just to confirm, the players experiencing these issues do have "Fix UI lag" enabled in the FiveM settings?

**Comment by RosenIgn** [comment]
Well, I don't think we have something that is taking over the NUI focus because the issue is happening very randomly and not at all players at the same time. And yes the players experiencing these issues have this feature enabled in the FiveM Settings. He just said that after enabling this feature the issue is not happening too often for now.

**Comment by RosenIgn** [comment]
Here is 1 more ticket from a player:

Screenshot: https://i.imgur.com/lmbDQwq.png
His message: at the electricians, I press the given letter, but it reports as an error(failed)

**Comment by SneakyAF** [comment]
Just a random thought - I can see you are Russian or something similar. Do you set your keyboard language to US when playing? It could be that you are trying to press 'A' but the equivalent key in your keyboard language is registered instead. I'm not familiar with the Russian keyboard layout but I think you know what I mean

**Comment by LukeWasTakenn** [comment]
I did just test it with a cyrillic keyboard and yes, it will count as a fail, which I guess does make sense.

**Comment by RosenIgn** [comment]
Oh, I see. So what can we do in this case? Should we notify the people? The strangest thing about this issue is that it's happening only to some players. For example, I tested it as well with a Cyrillic keyboard(Bulgarian phonetic traditional keyboard) and it's still working and I don't get fails.

**Comment by RosenIgn** [comment]
Well, we tested it and we saw that the issue is from the Cyrillic keyboard. But the strangest thing here is that it's counting as a fail only if you join the server with the Cyrillic keyboard then the issue is happening. If you switch the language in the game(in the server) and try it it's still counting as a fail. We just checked the code of your skill bar and we saw that you are using "event.key" for the keybindings so that's why it's counting as a fail if you use another keyboard. So we thought that it could be fixed using the key codes or something other. Please let me know your thoughts. Have a nice evening.

**Comment by LukeWasTakenn** [comment]
> But the strangest thing here is that it's counting as a fail only if you join the server with the Cyrillic keyboard then the issue is happening

I imagine this is due to some way that FiveM/CEF handles the inputs, not exactly sure.

Codes would be a possible solution but it could also be a potentially breaking change 🤔

**Comment by qwezertino** [comment]
So, the simple resolve for this problem its modify keyHandler function inside indicator.tsx file like that:

```
const keyHandler = useCallback(
    (e: KeyboardEvent) => {
      const capitalHetaCode = 880;
      const isNonLatin = e.key.charCodeAt(0) >= capitalHetaCode;
      var convKey = e.key.toLowerCase()
      if (isNonLatin) {
        if (e.code.indexOf('Key') === 0 && e.code.length === 4) { // i.e. 'KeyW'
          convKey = e.code.charAt(3);
        }

        if (e.code.indexOf('Digit') === 0 && e.code.length === 6) { // i.e. 'Digit7'
          convKey = e.code.charAt(5);
        }
      }
      setKeyPressed(convKey.toLowerCase());
    },
    [skillCheck]
  );
  ```
