### ISSUE TITLE
[Bug] Input dialog slider steps are incorrect

### ISSUE THREAD

**Issue by edwardexo** [overextended/ox_lib#414]
**Describe the bug**
Input dialog slider steps are incorrect.

**To Reproduce**
1. Create a slider with min/max/step values of 0/1/0.1
2. Put the slider to the third step (0.3)

**Expected behavior**
The slider value should be 0.3.

**Actual behavior**
The slider value is 0.3000000000000004

**Screenshots**
![image](https://github.com/overextended/ox_lib/assets/118666903/c879e430-922f-4d06-bb0b-5ebd7ea0ae96)
![image](https://github.com/overextended/ox_lib/assets/118666903/e89c56fc-5784-4568-ab17-dc6a238a08eb)
![image](https://github.com/overextended/ox_lib/assets/118666903/1f3f2f73-b647-4c18-a87e-fe845e2b2a59)
![image](https://github.com/overextended/ox_lib/assets/118666903/d7b6f262-a688-434a-93a9-7ead5abdfff0)

**Comment by LukeWasTakenn** [comment]
This is a JavaScript issue, you can even reproduce it by typing `0.1 + 0.2` in the devtools console.

**Comment by edwardexo** [comment]
Yes, that was my guess as well. Just thinking maybe it can be handled/fixed somehow in the slider to show correct values.
