### ISSUE TITLE
[Suggestion] Disable radial on player death

### ISSUE THREAD

**Issue by jumalley** [overextended/ox_lib#415]
**Is your feature request related to a problem? Please describe.**
Right now the radial menu can be open while you're dead, the actions listed in the radial menu can be abused in the meanwhile.

**Describe the solution you'd like**

```lua
local isActionsLimited = false

---Toggle player limitations
---@param limited boolean
function setLimitation(limited)
    isActionsLimited = limited
end
exports('setLimitation', setLimitation)

---Check if the player is currently limited
---@return boolean
function isLimited()
    return isActionsLimited
end
exports('isLimited', isLimited)

RegisterNetEvent('ox_lib:toggleLimitation', function(_state)
    setLimitation(_state)
end)
```

Credits : [scully_emotemenu](https://github.com/Scullyy/scully_emotemenu)

**Additional context**
Image [
![image](https://github.com/overextended/ox_lib/assets/50602425/bb07cbaa-740a-459d-aeae-489fb94e006b)
](url)

**Comment by LukeWasTakenn** [comment]
The lib is standalone, you can handle for this yourself using [lib.disableRadial](https://overextended.dev/ox_lib/Modules/Interface/Client/radial#libdisableradial).

**Comment by jumalley** [comment]
Okay perfect I didn't see that exports, thanks !
