### ISSUE TITLE
[Bug] Menu: Mouse doesn't show up

### ISSUE THREAD

**Issue by Preises** [overextended/ox_lib#418]
When using the Ox_lib interface Menu (lib.registerMenu) the mouse doesn't show up. Reporting this on version 3.9.0. However, the mouse works perfectly fine when using the alert dialog, context menu, or input dialog. Its just not working for the normal menu.

**Comment by LukeWasTakenn** [comment]
![image](https://github.com/overextended/ox_lib/assets/39926192/f053ec19-1424-4f01-b51f-b0d1e4a3dc01)
