### ISSUE TITLE
[Suggestion] Only listen for available inputs for skillchecks

### ISSUE THREAD

**Issue by Sojobo** [overextended/ox_lib#419]
Right now a skillcheck will cancel out as failed if you press any input, regardless of whether it's an acceptable input or not, by acceptable I mean one of the available inputs provided in the functions call. This means that if I press my push to talk button for example, the skillcheck will fail.
For my use-case, I'm throwing up a skillcheck when someone is cuffed to allow them an attempt to break those cuffs - the issue is when the skillcheck is thrown up on their screen it tends to be a high-action moment when the player is likely hitting other buttons to evade the police or attempting to talk or communicate through voice. 

lib.skillCheck(difficulties, { '1', '2', '3', '4' })

In my use-case only listening for keys 1-4 would mean the player gets a proper shot at the minigame without interfering with normal gameplay.

**Comment by LukeWasTakenn** [comment]
I can see this perhaps being a preference thing, and getting your community to heart the issue won't help it get pushed.

**Comment by LukeWasTakenn** [comment]
This is now the default behavior, though I am still open to the discussion from others whether it should be.

@Sojobo please let me know if it works as expected by pulling the latest commits and building the UI.

**Comment by Sojobo** [comment]
Tested locally and looks to work just as expected for my breakout script - ox_doorlocks still seems to operate as it did before (although I noticed I can push to talk), I have no issue with that as it's something the player would expect to be on screen, thought I'd mention it though just incase it was supposed to also follow the same behaviour - but yeah, I'll be pushing this live today and I'll be able to confirm/test on a much wider scale at that point.
Thanks for taking the time to make this change, you're going to make a lot of people very happy 😁
