### ISSUE TITLE
[Bug] multi-select type breaks input dialog

### ISSUE THREAD

**Issue by ali-exacute** [overextended/ox_lib#424]
**Describe the bug**
`multi-select` type break the menu

**To Reproduce**
add a `multi-select` inside your inputDialog , it will throw an error

**Expected behavior**
Should open the menu

**Screenshots**
![image](https://github.com/overextended/ox_lib/assets/16070339/e8d18d1b-895a-4807-865d-cc64dcc78cc3)

**Comment by LukeWasTakenn** [comment]
Error is due to incorrect usage.
