### ISSUE TITLE
context menu metadata progress color

### ISSUE THREAD

**Issue by ItzTrivial** [overextended/ox_lib#430]
**Is your feature request related to a problem? Please describe.**
I wanted to use the metadata progress to display the state of vehicles in my garage and I wanted to color them depending on the %.

**Describe the solution you'd like**
Adding an argument to the metadata array {label, value, progress, colorScheme}

**Comment by sleepyexe** [comment]
https://github.com/Lunar-Scripts/lunar_garage/blob/b381fe6b49f3a34b168dbb50104e469cc3158e32/client/main.lua#L106

**Comment by ItzTrivial** [comment]
Thats not what I meant. If I want to display multiple progressbars as metadata I dont want them all to have the same color
