### ISSUE TITLE
[Suggestion] - chat and chat-theme

### ISSUE THREAD

**Issue by Mesrine67** [overextended/ox_lib#433]
**chat and chat-theme.**
a system that resembles cc-chat and cc-rpchat
an owner menu, to activate/deactivate the display of connections/connections, send announce, egt maybe other options
emoji system, preview photo/screen/png/jpg/url and other
owner menu to configure the overextended resource convar present on the server

**Comment by LukeWasTakenn** [comment]
Out of scope.
