### ISSUE TITLE
[Suggestion] - sound system, use the same function as xsound/interactSound

### ISSUE THREAD

**Issue by Mesrine67** [overextended/ox_lib#434]
**sound system.**
use the same function as xsound/interactSound
maybe even the same thing as pmms but better?
a tablet interface to interact on a tebex site example?

**Comment by Ehbw** [comment]
You shouldn't really be using NUI to play sound (like those resources do), especially now with guides on how to create native audio (https://github.com/ChatDisabled/nativeAudio/)
