### ISSUE TITLE
[Bug] - Skill Check Forced Close

### ISSUE THREAD

**Issue by sleepyexe** [overextended/ox_lib#438]
**Describe the bug**
Skill Check forced close if triggered with ox_target, if the inputs key is nil the skill check will forced to close if target is active

**To Reproduce**
1. Should added value on inputs on the skill check options

**Comment by sleepyexe** [comment]
i.e 
![image](https://github.com/overextended/ox_lib/assets/67649181/0a1aadc5-7acb-445d-87ee-86a0d37751b0)

**Comment by LukeWasTakenn** [comment]
Are you on latest?
