### ISSUE TITLE
[Feature Request] Dialog add support for Number field

### ISSUE THREAD

**Issue by benzon** [overextended/ox_lib#44]
Hey,

So i got a couple of requests for the dialog, think it would make it even better.

On [Enter] it should submit the dialog.

And support for number input field would be brilliant.

**Comment by LukeWasTakenn** [comment]
Both features added in 518360727921e59e1b76f4b70c4c032bfaf7b269 and a3b8154b3e55ff16a70597fc78836bc7bcf48683
