### ISSUE TITLE
[Bug] RedM Menu Error due to unknown native (HudWeaponWheelIgnoreSelection)

### ISSUE THREAD

**Issue by RexShack** [overextended/ox_lib#440]
**Describe the bug**
We are using ox_lib in our RedM build, but when attempting to use the Menu we see an error when opening the menu.

attempt to call a nil value (global 'HudWeaponWheelIgnoreSelection')

**To Reproduce**
1. Setup ox_lib in a RedM server enviroment
2. build a standard menu in acordance with doc https://overextended.dev/ox_lib/Modules/Interface/Client/menu
3. Open the menu
4. See error in [F8]

**Expected behavior**
Menu should appear without error, by commenting out line 60 the error clears.

**Screenshots**
![Screenshot 2023-10-11 190315](https://github.com/overextended/ox_lib/assets/76662933/35dc0c83-67b3-4311-8695-e0e91c543e70)
![image](https://github.com/overextended/ox_lib/assets/76662933/ba3f3fb1-cb9a-44a4-aa2e-6a5970d700b4)

**Additional context**
(https://github.com/overextended/ox_lib/blob/f9a7df6422ae7ad45895365e3cbe52d412db6085/resource/interface/client/menu.lua#L60C21-L60C50)

**Comment by thelindat** [comment]
None of ox_lib is designed with RedM in mind.

**Comment by RexShack** [comment]
so are you saying that ox_lib is not going to support redm, if that is the case I need to rethink RSG framework

**Comment by LukeWasTakenn** [comment]
He's saying that none of ox_lib was designed with RedM in mind.

RedM support for it was PRed, if you fix this issue for RedM, feel free to PR.

**Comment by LukeWasTakenn** [comment]
"Resolved" in #445
