### ISSUE TITLE
[Bug] Value cannot be converted into a number

### ISSUE THREAD

**Issue by SuperMan-Sam** [overextended/ox_lib#467]
When I use color input, the return value appears with this prompt "Value cannot be converted into a number (received eb4034)"
the code:
local input = exports.ox_lib:inputDialog('Color', {
        { type = 'color',    label = 'Colour input',   default = '#eb4034' },
    })
local rgb = lib.math.torgba(input[1])

**Comment by SOH69** [comment]
> When I use color input, the return value appears with this prompt "Value cannot be converted into a number (received eb4034)" the code: local input = exports.ox_lib:inputDialog('Color', { { type = 'color', label = 'Colour input', default = '#eb4034' }, }) local rgb = lib.math.torgba(input[1])

After analyzing the code, i see that the function actually doesn't purpose what you want to achive, here you are trying to convert hex to rgba
I can suggest you to do chatgpt and get a hex-rgba converter snippet
