### ISSUE TITLE
[Bug] lib.getClosestVehicle 3.14.0

### ISSUE THREAD

**Issue by CzlowiekNinja2021** [overextended/ox_lib#475]
**Screenshots**
![image](https://github.com/overextended/ox_lib/assets/89016106/e02f4de2-273d-47ed-98dc-1d074da95b03)

**Additional context**
```
lib.callback.register("localmechanic:diagnostic", function(vehicleNET)
	local closetVehicle = lib.getClosestVehicle(GetEntityCoords(PlayerPedId()), 5.0, false)
	print(closetVehicle)
end)
```

**Comment by D4isDAVID** [comment]
Delete the `ox_lib` resource folder ***completely*** and then add the latest release again. If you still have this error then read this again; you need to ***delete*** the `ox_lib` folder first.
