### ISSUE TITLE
[Bug] - SCRIPT ERROR: citizen:/scripting/lua/scheduler.lua:90: Unable to load UI. Build ox_lib or download the latest release.

### ISSUE THREAD

**Issue by ChlxeThomson** [overextended/ox_lib#479]
**Describe the bug**
Downloaded the latest version, put the folder into my **[STANDALONE]** folder, **ensure ox_lib** after **ensure qb-core** in my **CFG** and its throwing out the error its not the latest version when it is?????????????? 

Qbcore framework version = Latest one, 5 days old

**Expected behavior**
For it to work obvs with no errors.

**Screenshots**
<img width="568" alt="Screenshot 2024-01-10 201806" src="https://github.com/overextended/ox_lib/assets/58238399/c00c2db6-efbe-4034-b325-17565a309ac8">
<img width="330" alt="Screenshot 2024-01-10 202155" src="https://github.com/overextended/ox_lib/assets/58238399/7a22e47f-9f59-4586-895f-f175a5ccd471">

**Additional context**
Would kindly like some help please, thank you

**Comment by StuxxyOfficial** [comment]
Did you read the error?

Do as it says.

**Comment by Scullyy** [comment]
Same issue here, someone needs to seriously fix this asap. Like what are people like you and myself who don’t know how to follow instructions going to do? Do they expect us to read and download from the releases section? If so they need to remember that I’m a server owner and entitled to support!!!

**Comment by CoZmoTheGod** [comment]
You shouldn't use ox_lib if your brain cells are not firing correctly. There's even an idiot print in the console for idiots.

**Comment by Randolio** [comment]
I tried to use this on Roblox and nothing happened
