### ISSUE TITLE
[Suggestion] Add Menu Functionality

### ISSUE THREAD

**Issue by LynxarA-Coding** [overextended/ox_lib#481]
I am trying to use ox_lib menu instead of ScaleformUI menu, but it lacks functionality. Preferred enhancements:
- Ability to set index to elements (to save user input) 
- Ability to create Side-Menus (menu apperars on the right/left if a certain option is selected/hovered)
- Ability to create banners for menus
- Ability to get index of selected or not-selected options (for example, when option 1 is selected, it changes behaviour based on another option selection)

**Comment by LukeWasTakenn** [comment]
You can do 1 and 4, and there's no plans for side menu or banners for the menu.
