### ISSUE TITLE
[Bug] inputDialog not accessible if a menu is open

### ISSUE THREAD

**Issue by Mesrine67** [overextended/ox_lib#488]
### Feature Request: Dialogue System with Non-Blocking Input Dialog

**Description:**

I am working on implementing a dialogue system for admins within the game. My goal is to enable admins to write new messages without needing to close the existing menu. However, I've encountered an issue where opening an `lib.inputDialog` without closing the menu first makes the `lib.inputDialog` unresponsive to interactions.

**Proposed Solution:**

Would it be possible to enhance the `lib.inputDialog` function by adding a style property similar to what is available in `lib.showTextUI`? Specifically, I am looking to add a `zIndex` property to ensure the `lib.inputDialog` appears above the menu and remains interactive.

Here's an example of what the implementation might look like:
add `style` to options
```lua
local input = lib.inputDialog('Ecrire un message', {  
    {
        type = 'textarea',             
        label = 'Message',         
        description = 'Saisissez votre message ici.',
        placeholder = 'Votre message',
        required = true,               
        rows = 3,                      
        cols = 40,                     
        autosize = true,
    },
}, 
{
    allowCancel = true,
    style = {
        zIndex = 9999
    }
})
```

This change would significantly improve the usability of dialogues in scenarios where multiple UI layers are active.

**Visual:**

![2024-01-24 02-40-10](https://github.com/overextended/ox_lib/assets/89279156/1402fdba-72fc-47e3-b639-e58382dd5e4b)

**Comment by LukeWasTakenn** [comment]
Due to how the NUI focus works for the list menu (it always tries to take priority), I don't think there's much that can be done about this.

You should be hiding the menu before opening the dialog.

**Comment by Mesrine67** [comment]
ok thanks luke
