### ISSUE TITLE
[Suggestion] Sliders

### ISSUE THREAD

**Issue by LSatan** [overextended/ox_lib#490]
Get the value of a slider back immediately after a change. (Interface/input dialog)

Or add slider to the menu as the menu has direct callbacks.

The possibilities would be varied, similar to checkbox callback and other things.

**Comment by LukeWasTakenn** [comment]
Not going to happen as the input dialog is designed as a form rather than a live update thingy

**Comment by LSatan** [comment]
add slider to the menu as the menu has direct callbacks!
