### ISSUE TITLE
[Bug] Radial Menu not working

### ISSUE THREAD

**Issue by DjQuro** [overextended/ox_lib#492]
**Describe the bug**
Radial Menu not opening after Update on our Live System

**To Reproduce**
1. Update ox_lib to the latest version on dev-Server (Copy of Live Server)
2. Verirfying it running there
3. Copy the same Script to Live System
4. No Error Reportings in Console. Should be working
5. Disappointment

**Expected behavior**
Pressing Y (or Z depending on KBD-Layout)

**Screenshots**
**Generic GTA5 Screen without ox_lib Radial here**

**Additional context**
Dependencies are starting so there must be something working

**Comment by bluelineparabellum** [comment]
I can also not open mine for some reason.. New update

**Comment by DjQuro** [comment]
> I can also not open mine for some reason.. New update

I tried to get back one version and it was not working either.

**Comment by bluelineparabellum** [comment]
I had to create my own script and added radial items to it.

> > I can also not open mine for some reason.. New update
> 
> I tried to get back one version and it was not working either.

**Comment by jag3dagster** [comment]
> I had to create my own script and added radial items to it.

Yes that is how the radial menu works. There are no default options set for it, and if there are no options it won't be displayed.

**Comment by DjQuro** [comment]
> > I had to create my own script and added radial items to it.
> 
> Yes that is how the radial menu works. There are no default options set for it, and if there are no options it won't be displayed.

We have installed a Script which provides these options. On Dev and Prod. Guess what... Dev is working, Prod not. Bothe Scripts are exact the same.

So it's still not working.

**Comment by jag3dagster** [comment]
> Dev is working

But you literally said it is working. No one here has any insight into the difference to your dev and prod servers, that is something you're going to have to investigate on your own.

**Comment by LukeWasTakenn** [comment]
A difference between only windows wouldn't cause your radial menu in the game to not appear.

Are you using source code or release? If you're using source code make sure you compile the web files.

Are you sure you have at least 1 global radial menu item on the prod server so that the radial menu meets the condition to appear?
