### ISSUE TITLE
[Suggestion] Add disableAllControlAction(0) to progress options

### ISSUE THREAD

**Issue by BostonGeorgeTTV** [overextended/ox_lib#495]
Hello and sorry for the inconvenience. Would it be possible to add an option to disable any type of character control while a preogressbar is active?
I already did it, here's the code, thanks.

in ox_lib/resource/interface/client/progress.lua

line 23
`---@field disable? { controls?: boolean, move?: boolean, sprint?: boolean, car?: boolean, combat?: boolean, mouse?: boolean }`

line 125/126/127
`if disable.controls then
    DisableAllControlActions(0)
end`

**Comment by Andyyy7666** [comment]
@dandi83 create a pr instead of writing the code here, would be faster and better.

**Comment by dandi83** [comment]
oh, sorry
