### ISSUE TITLE
[Suggestion]-[ox_lib]-[radial menu]-[joystick control]

### ISSUE THREAD

**Issue by Mesrine67** [overextended/ox_lib#497]
would it be possible to add the possibility of controlling the cursor with the joystick of the controller? and select with a button on the controller?

secondary touche [cfx separate binding manette](https://github.com/citizenfx/fivem/issues/2084#issuecomment-1618048798)

![image](https://github.com/overextended/ox_lib/assets/89279156/b2d234e7-35aa-4b43-9d1e-a013653d8cd8)

![image](https://github.com/overextended/ox_lib/assets/89279156/289853da-17b1-41e3-8f5d-ee8b14a7572f)

**Comment by LukeWasTakenn** [comment]
CEF doesn't support gamepad API.
