### ISSUE TITLE
[Bug] Weird behavior with the sliders

### ISSUE THREAD

**Issue by zf-development** [overextended/ox_lib#505]
**Describe the bug**
Check the video
It's hard to explain but it's really visible in the video.

https://github.com/overextended/ox_lib/assets/48424078/8f4a22fc-33a0-4717-bce9-baf52c404191

**Comment by zf-development** [comment]
Have you tried this? `(0.1 + 0.2).toFixed(1)`

**Comment by LukeWasTakenn** [comment]
> Have you tried this? `(0.1 + 0.2).toFixed(1)`

No, feel free to PR is you find a solution that doesn't hinder normal usage.
