### ISSUE TITLE
Problem with cache

### ISSUE THREAD

**Issue by extermi111** [overextended/ox_lib#51]
Hello.

I have a problem with my cache. On my local server I am unable to reproduce it, while it occurs quite often on our development and production machine. I can't really find a cause and effect relationship and I must admit that it makes using ox_lib quite difficult.

![image](https://user-images.githubusercontent.com/12661379/174773336-68d6aa31-1189-4769-9683-cb6b35e1db6b.png)

**Comment by thelindat** [comment]
Apparently people use a global git ignore and ignore any “cache” folder.

**Comment by extermi111** [comment]
Damn, you're right... I never would have thought to check such a simple thing.
