### ISSUE TITLE
ox_lib: invalid conversion (using ox_fuel)

### ISSUE THREAD

**Issue by Fcatalao** [overextended/ox_lib#52]
![image](https://user-images.githubusercontent.com/856855/175053178-5c49512d-fc4c-491e-ae47-e72bbf071204.png)

This happens with ox_fuel using after the lib.progressCircle ends. 

`	CreateThread(function()
		lib.progressCircle({
			duration = duration,
			useWhileDead = false,
			canCancel = true,
			label = "Fuelling..",
			disable = {
				move = true,
				car = true,
				combat = true,
			},
			anim = {
				dict = isPump and 'timetable@gardener@filling_can' or 'weapon@w_sp_jerrycan',
				clip = isPump and 'gar_ig_5_filling_can' or 'fire',
			},
		})

		isFueling = false
	end)`

**Comment by LukeWasTakenn** [comment]
What locale are you using?
