### ISSUE TITLE
[Suggestion]  Add var to lib.raycast.cam(FLAG, IGNORE, DISTANCE)

### ISSUE THREAD

**Issue by iafondo** [overextended/ox_lib#521]
having to change stuff due this not having the option of taking player head coords as mesuring point of the raycast because this will work well when player is in first person but sucks when 3rd(comes out short due camera pos changing), adding an option so it asks if head is the root location a simple true or false would be great so you can choose to have always the same pos where the raycast is spawning. 

lib.raycast.cam(FLAG, IGNORE, DISTANCE, PLAYERHEADCOORDS BOOLEAN or RayRootPos)

**Comment by thelindat** [comment]
I simply haven't been bothered to add more to the module, but raycast.cam is _from the camera_ - a different function would needed for using the head as a starting point.

**Comment by iafondo** [comment]
> I simply haven't been bothered to add more to the module, but raycast.cam is _from the camera_ - a different function would needed for using the head as a starting point.

i fixed it, not exacly like it would be by a pro but it works as intended: 
![git2](https://github.com/overextended/ox_lib/assets/85797833/b8f5c512-4f57-4e82-ab0a-5c9e7caba9eb)
![git1](https://github.com/overextended/ox_lib/assets/85797833/bb5e9633-d549-4507-9492-3bebc503ca83)
