### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by LawlessCitizen** [overextended/ox_lib#527]
![bug](https://github.com/overextended/ox_lib/assets/150984568/7bd1ca17-8759-4eea-bc6f-896a7cd3e010)

**Comment by LawlessCitizen** [comment]
started when i put the new ox_lib server was fine before that

**Comment by thelindat** [comment]
Not a bug, it just means the model could not load in the timeframe.

**Comment by LawlessCitizen** [comment]
what is the time frame?
