### ISSUE TITLE
[Suggestion to improve] Edit the progress bar and replace it with "progressbar" in qbcore

### ISSUE THREAD

**Issue by iTS-RoBeR** [overextended/ox_lib#537]
It would be nice to be able to edit the progress bar because there are servers that use their own and right now it looks ugly to have different progress bars in an interface. In addition to including the lib notifications, which hopefully can also be replaced

**Comment by Demigod916** [comment]
the code is open source. you can do whatever you want with the progressbar. as far as having 2 different progressbars in your server, isnt that more of a development issue for you rather than the ox dev team?
