### ISSUE TITLE
[Bug] Increased waitFor errors

### ISSUE THREAD

**Issue by Manason** [overextended/ox_lib#547]
**Describe the bug**
Upgrading to v3.19 has increased waitFor errors as reported by several Qbox users. I also saw this myself when upgrading from v3.18 and subsequently downgraded.

**Screenshots**
https://cdn.discordapp.com/attachments/1118364689588572170/1227385556564967494/image.png?ex=662836e0&is=6615c1e0&hm=de93534cab82106fd9e3045daf44dcb36bb0deb795e439878f74168234aacd86&

**Comment by thelindat** [comment]
I do not give a fuck. Search discord for the answer to this constant pestering question - this is not an ox_lib issue.

**Comment by Manason** [comment]
What was the change made exactly? Changing the timeout to use game timer instead of frame rate?

**Comment by thelindat** [comment]
> reported by several Qbox users

![image](https://github.com/overextended/ox_lib/assets/65407488/8058d2b3-e04c-4835-900c-0f1c5f16db19)
![image](https://github.com/overextended/ox_lib/assets/65407488/9c7487dd-d57a-4118-8633-4e3922dcca0c)
