### ISSUE TITLE
[Bug] Notification progress circle timer not reset.

### ISSUE THREAD

**Issue by zf-development** [overextended/ox_lib#554]
**Describe the bug**
The circle around the icon in the notifications is nice but, when multiple notifications are sent with the same id, the timer is not reset so it looks like this even if the notification is going to be there for 10 more seconds for exemple
![image](https://github.com/overextended/ox_lib/assets/48424078/3ba170b0-298d-474c-9c97-63956c8b34d7)

The circle around the background of the icon is not there anymore.

**To Reproduce**
1. Send multiple notifications with the same id.

**Expected behavior**
The timer will start for the first notification sent but it you send another one with the same id while the timer is going down, it won't be reset.

**Screenshots**
![image](https://github.com/overextended/ox_lib/assets/48424078/d8edc848-c863-4395-b33a-4062a55a054f)

**Comment by zf-development** [comment]
Here's a video to show it live.
Bottom left, you can see when I press E to send a notification.
Top Right, you can see the timer and notification.
https://github.com/overextended/ox_lib/assets/48424078/9c8e22dc-7c75-4c20-ba13-3fc71946f967

**Comment by LukeWasTakenn** [comment]
@RrybaN You wanna have a look at this one?

**Comment by RrybaN** [comment]
Okay, will have this fixed.
