### ISSUE TITLE
[Bug] [ script:ox_inventory] SCRIPT ERROR: @ox_lib/imports/require/server.lua:82

### ISSUE THREAD

**Issue by ElNemo22** [overextended/ox_lib#556]
**Describe the bug**
I don't know why this error occurs

**To Reproduce**
Install ox_lib and ox_inventory

**Screenshots**
![image](https://github.com/overextended/ox_lib/assets/95186066/dd1aa780-cf51-4b87-84ff-5cbf0560f5cb)

**Comment by Demigod916** [comment]
Can we see the full error?

**Comment by ElNemo22** [comment]
> Can we see the full error?

I get another error that can be fixed but I still haven't restarted the server because of that. and the file named in the image does not exist either

**Comment by thelindat** [comment]
🤡
