### ISSUE TITLE
[Suggestion] - Add GET_VEHICLE_HAS_FLAG to vehicleProperties

### ISSUE THREAD

**Issue by Mesrine67** [overextended/ox_lib#561]
I just found this, it might be better to add it for management, the first thing I saw these: FLAG_NO_BOOT This vehicle should not be considered for boot inventory.
These are just too good, right?

**Additional context**
[github pull cfx.](https://github.com/citizenfx/fivem/pull/2340)

**Comment by thelindat** [comment]
That would depend on cfx merging a community PR.
