### ISSUE TITLE
[Bug] Error ox_lib I don't know how to fix it?

### ISSUE THREAD

**Issue by BlueKillerTV1** [overextended/ox_lib#562]
Hello,

I'm encountering an error with ox_lib, and the person I bought my custom script from is telling me that the issue lies with ox_lib. I'm not sure how to fix something like this, so I'm reaching out as a Script error. I hope you can assist me in getting it fixed so it works again. I don't know how to proceed and would appreciate any help in resolving this error.
![ox_lib error](https://github.com/overextended/ox_lib/assets/67653517/fd99b6e2-6064-4ced-9d49-daaa40c79552)
https://gyazo.com/25c106e60da7d96df6569993dbfe1095

**Comment by tom-osborne** [comment]
Both errors are telling you to start `ox_lib` before both resources, so fix your start order in your `server.cfg`.

**Comment by BlueKillerTV1** [comment]
Hello, it's still showing the same error. I don't know how to fix it; it seems like I've tried everything now.

https://gyazo.com/44eb59483a201b791286da1d82494d08
