### ISSUE TITLE
[suggestion] Rightclick support for Context menu

### ISSUE THREAD

**Issue by zRxnx** [overextended/ox_lib#571]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
A option to configure the left and rightclick.
For example: (very simple example)
```lua
rightclick = function()
      ExecuteMyFunction()
end
```

**Comment by LukeWasTakenn** [comment]
Not going to happen.

Right click is unintuitive and bad UX design, plus it's already a *context* menu so using a right click to do something makes no sense.
