### ISSUE TITLE
[Suggestion] Allow some configurable defaults for Interface

### ISSUE THREAD

**Issue by xhorntail** [overextended/ox_lib#579]
**Is your feature request related to a problem? Please describe.**
Nope.

**Describe the solution you'd like**
Apologies if this exists and I've overlooked it.
The ability to configure some of the Interface defaults without having to edit/pack the TS would be quite nice.

**Additional context**
The specific components I find myself replacing (with the same values) in every call:
- Notification default duration
- Notification default sound/audio
- Notification position
- TextUI position

A few reasons I feel these options are necessary
- It seems that often times, ~500ms or so has already passed on the timer by the time notifications are displayed, leaving 2500 for the player to read the notifications.
- Many scripts (including escrowed) have a nasty habit of spamming several notifications at once, and many of them don't give access to the invoking function in order to explicitly adjust the times.
- Without audio by default, the player has to visually notice the notification in the far-right corner of the screen before beginning to read it.
- All of the above can lead to rather common occurrences of giving the user 800-1200ms to actually read a 1-3 line notification once they have noticed it, which in some cases can't be extended through the call.
- I don't meant to offend anyone, but that seems highly optimistic of the average players reading speed.

**Comment by Mesrine67** [comment]
+ position menu

**Comment by Moozdzn** [comment]
Everything you are requesting can already be done in the file itself [notify.lua](https://github.com/overextended/ox_lib/blob/master/resource/interface/client/notify.lua)

> It seems that often times, ~500ms or so has already passed on the timer by the time notifications are displayed, leaving 2500 for the player to read the notifications.

You can copy how the position is set and apply it to the duration
https://github.com/overextended/ox_lib/blob/8712c9b0c9481e9bfb0cb33dff765252f712bfb5/resource/interface/client/notify.lua#L28
```lua
data.duration = data.duration or 2500
```

>Many scripts (including escrowed) have a nasty habit of spamming several notifications at once, and many of them don't give access to the invoking function in order to explicitly adjust the times.

read above

> Without audio by default, the player has to visually notice the notification in the far-right corner of the screen before beginning to read it.

read above

> The ability to configure some of the Interface defaults without having to edit/pack the TS would be quite nice.

If you are talking about the UI, you dont need to edit it. If you mean the npm package, it just calls the lua exports https://github.com/overextended/ox_lib/blob/8712c9b0c9481e9bfb0cb33dff765252f712bfb5/package/client/resource/interface/notify.ts#L31

**Comment by LukeWasTakenn** [comment]
As explained by @Moozdzn, all of these things are very easily edited by intercepting the nui message calls in their respective lua files, you don't need to edit the UI files for any of these at all.
