### ISSUE TITLE
lib.callback fails when no *CALLBACK* function is passed

### ISSUE THREAD

**Issue by kirianmladen** [overextended/ox_lib#587]
Since the update an hour ago, I can't even join my server normally anymore without this problem. 
I can't choose a character...

![image_2024-05-23_010527761](https://github.com/overextended/ox_lib/assets/76671247/ba9397d2-d694-434d-bc96-07fc57fde937)

**Comment by thelindat** [comment]
Blame the people who decided to completely misuse the function and treat it as a regular "fire and forget" event.
