### ISSUE TITLE
[Bug] Progress Bar stuck?

### ISSUE THREAD

**Issue by SeaLife** [overextended/ox_lib#617]
**Describe the bug**

The progress bar sometimes does not finish and stays at a 100%. Sometimes you can abort the progress bar and just do the action again and it works. Sometimes you have to reconnect (this may be our fault in the code, idk)

https://youtu.be/zH5pur7pbmM

**To Reproduce**
I dont know how to reproduce this issue. There is no error message in F8 nor the server console, the Bar just stucks. I also cant reproduce or provoke this on my own computer, this clips is from a player of our server.

The code for this progress bar looks like this:
```lua
        local isAborted = not lib.progressBar({
            duration = (counterLength * counterEnd) - 100,
            label = 'Arbeite ...',
            useWhileDead = false,
            canCancel = true,
            disable = {
                car = true,
                move = true,
                combat = true,
            },
            anim = marker.data.farm.oxLibAnim
        })

        if isAborted then
            if marker.data.farm.onAbort then marker.data.farm.onAbort(ped, object) end
        end
```

**Expected behavior**
I expect the progress bar to finish and proceed with the remaining code.

**Screenshots / Video**
https://youtu.be/zH5pur7pbmM

**Additional context**
ox_lib in the newest version tested. Ped is sitting in a vehicle.

**Comment by LukeWasTakenn** [comment]
Can you try like a 100 tick wait between running the progress bars and see if that makes a difference?
