### ISSUE TITLE
[Feature Request] Ability to open inventory with active progressbar.

### ISSUE THREAD

**Issue by Marcinekk** [overextended/ox_lib#62]
Hi. When progressbar is active there is no option to use inventory (ox_inventory). In some cases it's problematic, so maybe ability to unlock inventory too like

> disable = {
>     inventory = true, -- true/false
> },

**Comment by thelindat** [comment]
There is (was?) some problematic behaviour that can occur like desync in some situations, which this lazily solves without needing everyone to perform a bunch of annoying checks.

Just set invBusy back to false if it's an issue for your situation.
