### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by NinaRatchett** [overextended/ox_lib#629]
**Describe the bug**
Interface issue at the field 'pos'.

**To Reproduce**
1. Go to any server with updated ox lib
2. Click on nothing
3. Scroll down to f8 screen

**Expected behavior**
Whenever I update ox lib to current I get an error message, but when I change it back it's fine.

**Screenshots**
Below

**Additional context**
N/A
![ox lib error](https://github.com/user-attachments/assets/51a15f47-81d0-4add-a944-8297d14bb9ef)

**Comment by thelindat** [comment]
So you somehow managed to request a prop be created, without assigning a position. No clue how that'd be "allowed" at any point previously.

**Comment by NinaRatchett** [comment]
So this is unfortunately with qs inventory when trying to use consumables via through the inventory. But I fixed my issue tho
