### ISSUE TITLE
[Bug] Raycast from far camera won't work

### ISSUE THREAD

**Issue by iSentrie** [overextended/ox_lib#652]
**Describe the bug**
Using camera modes that are a little further from ped, breaks raycast.

**To Reproduce**
1. Simply switch between camera modes and try to raycast
2. It wont work on the farthest one and +- from the middle one

**Expected behavior**
Properly find a target on any camera view

https://github.com/user-attachments/assets/bc00b9b8-74c4-4657-a3f1-7a7078cd6454

**Comment by thelindat** [comment]
Did you define the distance of the raycast?

**Comment by iSentrie** [comment]
> Did you define the distance of the raycast?

Did it this way
```lua
local hit, entityHit, endCoords, surfaceNormal, materialHash = lib.raycast.fromCamera(2, 4, 5)
```

**Comment by thelindat** [comment]
..increase the distance.

**Comment by iSentrie** [comment]
Yeah clearly, I was used too much for distance from ped to target.
