### ISSUE TITLE
[Suggestion] Multiple Suggestions

### ISSUE THREAD

**Issue by Waves966** [overextended/ox_lib#72]
- Allow icon for number input type.
- Add min and max to number input type.
- Add a date input type.
- Allow inputs / context menu to have an image as a header instead of text? Maybe?
- A color input type?
- Allow inline inputs sort of how discord embeds allow inline fields

**Comment by Waves966** [comment]
Another Suggestion: Allow arrow = false to remove the arrow when using the menu param in context menu. I find that the arrow clutters the menu and this would allow disabling the arrow for certain menus

**Comment by LukeWasTakenn** [comment]
Some of this has been implemented, date (and maybe color) input will come some time in the future and there are no plans for the rest.
