### ISSUE TITLE
[Suggestion] Functions support

### ISSUE THREAD

**Issue by xDope7137** [overextended/ox_lib#73]
A function support for context menu. Its tedious to create events for each buttons. If there was a function like "action" in qb-target, it would become way easier to work with context menu. Especially when the menu is just doing simple thing on client side.

**Comment by LukeWasTakenn** [comment]
Added in commit 0e7bd1a177d90de9e87794377c193baa7c36ddc7.

You'll be able to define a `onSelect` function in a menu option that returns passed args like so:
```lua
onSelect = function(args)
    print(json.encode(args, {indent=true})
end
```

**Comment by xDope7137** [comment]
It's not logical to have args for function in my opinion. The data is literally there to be passed through.
