### ISSUE TITLE
inputDialog does not open if last menu is just closed.

### ISSUE THREAD

**Issue by xDope7137** [overextended/ox_lib#74]
Issue : 

- If an inputDialog is open and if you open another inputDialog immediately after, it does not work. But if you add a 100ms delay, it opens. This is not a giant bug, but it took me a few minutes to debug this

https://streamable.com/t0dq32

**Comment by LukeWasTakenn** [comment]
Resolved in 82d052a1bb068eaeb24faebf80b547ce5dfa9206
