### ISSUE TITLE
Some Suggestion

### ISSUE THREAD

**Issue by ImClod** [overextended/ox_lib#79]
On The new menu creation it would be useful a option to check if a elements of the menu is clicked and not only selected

**Comment by LukeWasTakenn** [comment]
What?

The callback function when an element is clicked returns `selected`, `scrollIndex` and `args`.

**Comment by ImClod** [comment]
Oh nice it wasnt not so clear in docs, but yea it works thanks man and sorry

**Comment by LukeWasTakenn** [comment]
How is it not so clear in the docs? I'm confused.

![image](https://user-images.githubusercontent.com/39926192/187033223-b17d6f0b-b70d-4787-b57a-b05435659d57.png)
