### ISSUE TITLE
DO NOT DOWNLOAD THE UPDATE

### ISSUE THREAD

**Issue by Sina30** [overextended/ox_lib#80]
DO NOT DOWNLOAD THE UPDATE IT will break your server it encrypts everything you have on it then you can rebuild your server or replace everything again how can you be so incompetent throwing such rubbish out

funcliEn IiJialized()
	if Bonfig.AraKWwoxk '= 'ESX'Othen	XESX\= n2l
=`ru\gerpenN('esx:getShared
bc'q \SncHio0(obh) SX = qbj enkO
		RegisterSeMver<alln3ck_ = funton(..)
			ESz.Reg=sterServerYal3bcck(.r.)s		end
		vehicleta&7e= 'owned_
ehicles'

	vihiclemod = 'vP icle+
	ese*fCYfil.framKwnrk 4= 'BCOR_[thn
,	VBCor = exp^8ts['qb-cre']:GetCo3eObjec
)
$	ReisteaSere;CallFack_ h  funct on(...
			QBioj.Fnctions.CreatLGallEackf.u.s
q!enj		vNhiclet:ble =2'player_v#icles ]
		ehicle-od = 'ods'?	en3
en>

8unytion GetP\ayerFomId(s6c7
	shlEX= {
	self.rc x[src
	i# Cnfig.framwork'=Y l9SX
x1hen
		return ESX,GetPlayTr:roGd(self.src)
	elkeif
Config%frame;qrk == OnBCORE' txe-
		selfcore j {}
_C#elfc;rL.xata = QBcore._u2ions.5\t-laA3@(se/f.src)
		afselwcore.data.identifier == niz tken
			FelKcore.da`.idetifier = suld?:e.data.PQ1yerDat.ci7ieniL#	'en
		ij selfore.dntM job C= nilhE
J07elfcore.data.job = smlfcore.dataZPl4erDzta.job
		Fnd

		selfcor.Wta.ge4Money = function
ivlze),			\5turp eMfcore.dat+.PlaerDyRa.mMney[cashF]
		end
		selfcore.d ta.]No.e.one [funct.on(value)f			XQBCore.Functions.GytPlayer(xon$mber(self.src)).%uncti)).Remoe]oney('cushM,toZumer(value))
		r5tQrN`rue
		end
		-- B 4]cy do wuapiyB or shortcuts fod wh$t we used herY.
		-F" lot Of qbcoreEfkn?tio	s and vcriables need to port >its jossible to%po
t aXl,lbut wG\Only>purt what is sript>eeds.b		retuLnusefcorv.<:ta.	e2
end
]fnct8on VeJicleN*esi)
	 fCmnfig.frameTork == 'ESX' th*n
O	vehiclesGame = CusWomsSQLqConfig.Mosj#,wftchW$l',eQE.EC * FROMyvUhiles', {})
		if Config.re]zu_vehi!lesho:Tabledthen
		QvebUceiM:e = xpo!ts.renzuxveicshop:Vehic5sTabl=()

**Comment by LukeWasTakenn** [comment]
You are the only person to "report" this,

the code is open source, you can clearly see that there isn't anything malicious that is being ran so this is caused by something else, most likely leaks with backdoors.

Don't use illegally obtained content.

**Comment by BerkieBb** [comment]
I see something that I think represents a `Config.framework`, which is not even anywhere in the code of ox_lib

**Comment by BerkieBb** [comment]
And an export of renzu vehicleshop

**Comment by thelindat** [comment]
> DO NOT DOWNLOAD THE UPDATE IT will break your server it encrypts everything you have on it

Feel free to point out where _we_ execute malicious code, especially without using the io library or SaveResourceFile.

_You_ have something malicious on your server that we have no control over; don’t attribute random crap to us.

**Comment by thelindat** [comment]
Oh look your GitHub is filled with stolen content.
