### ISSUE TITLE
[Suggestion] Add checkbox to Menu Interface

### ISSUE THREAD

**Issue by Damien111** [overextended/ox_lib#83]
There are checkboxes in the input dialog, could they be added to the base menu interface? I might be wrong but I don't seem to see if that is a default option. Would be extremely useful for making toggle menus.

**Comment by LukeWasTakenn** [comment]
Tbh when I was making the menu the idea of checkboxes didn't really occur to me so to implement something like this there would probably need to some rewriting required as the UI is currently written around the idea of indexes and scroll indexes for list menu items.

However you can currently achieve the same effect as a checkbox by setting 2 values on an button item and then setting the default index to the one from the `onSideScroll` function callback.
