### ISSUE TITLE
FixedWidth doesn't  work

### ISSUE THREAD

**Issue by tony-stark-17** [overextended/ox_lib#88]
![image](https://user-images.githubusercontent.com/76168122/189173484-1ac2a95c-1d5f-4898-babf-3d1025360a64.png)

**Comment by tony-stark-17** [comment]
The Icon size makes the text uneven

**Comment by LukeWasTakenn** [comment]
Resolved in commit 5d4eff8cd38ccc45a02d1074cc1a2373d8f4095d.
