### ISSUE TITLE
[Suggestion] Modal

### ISSUE THREAD

**Issue by PoorLatency** [overextended/ox_lib#93]
Is it possible to add ~https://mantine.dev/core/modal/~.. I forgot this isn't  using Mantine my fault. Is it possible to add https://chakra-ui.com/docs/components/modal with the options to center the modal, change size, overflow inside the modal? For an example;

```lua
-- data: table
    -- header: string
    -- content: string
    -- size: 'xs' or 'sm' or 'md' or 'lg' or 'xl' (optional - default is md)
    -- centered: boolean (optional)
    -- overflow: boolean (optional)


local modal = lib.displayDialog({
	header = "text",
	content = 'General Kenobi  \n Markdown support!',
	size = "md",
	centered = false,
	overflow = false,
})
```

**Comment by LukeWasTakenn** [comment]
Could add some of this to the alert dialog, input dialog would be more difficult with the way the API is integrated with the heading and rows.

**Comment by PoorLatency** [comment]
> Could add some of this to the alert dialog, input dialog would be more difficult with the way the API is integrated with the heading and rows.

You can make it separated from alert box if you want.
