### ISSUE TITLE
Notification gets stuck on screen

### ISSUE THREAD

**Issue by DistrictZion** [overextended/ox_lib#94]
Hi,

I recently noticed an issue where notification don't go away. I do not if it is a bug or a problem with my scripts. Thought of reporting. 
![image](https://user-images.githubusercontent.com/78443434/189915047-5a98e2ab-aee4-456f-9bf5-0a19ec731d50.png)

I have also attached a screenshot of the said problem.. It's persistent and no other notification comes.

**Comment by LukeWasTakenn** [comment]
Gonna need the code for the notification and the code around the notification but this is most likely user error.

**Comment by DistrictZion** [comment]
function ESX.ShowNotification(message, type, length)
    lib.notify({
        id = 'esxnotifiication',
        title = 'Zion City Wire',
        description = message,
        position = 'top',
        style = {
            borderRadius = 7,
            backgroundColor = '##f51142',
            color = '#black'
        },
        icon = 'city',
        iconColor = '#ffffff'
    })  
end

I edited ESX default notification to do this . 🥲

**Comment by DistrictZion** [comment]
Ohh.. Alright.
Thanks :)

You may close this ticket. [def not an issue]
