### ISSUE TITLE
Zone Creator distorts box when changing heading

### ISSUE THREAD

**Issue by jag3dagster** [overextended/ox_lib#96]
**Description**
When creating a box zone, after changing the heading of the box, if the user changes the height or width of the box it will distort into a rhombus.

![FiveM_b2699_GTAProcess_2022-09-14_15 48 05](https://user-images.githubusercontent.com/77469789/190276501-31012894-fd3e-451e-9a65-dc139df43e92.png)

**Expected**
Box preview stays as a box

**Actual**
Box preview becomes a rhombus

**Repro Steps**
1. `/zone box`
2. Change heading of box with `Q` or `E`
3. Attempt to change Width (ctrl + scroll) or Length (alt + scroll)
4. Notice distortion of box

**Comment by DokaDoka** [comment]
rhombus is dead, fixed in [5efec8a](https://github.com/overextended/ox_lib/commit/5efec8a114500ac35e1082e0f722dbbb4e3a4c20)
